Repository conan-io/conan, pull requests merged in 2018-12, with the labels that each got.

#4033 fixing source bugs and issues
  conans/client/conan_api.py
  conans/client/installer.py
  conans/client/remote_manager.py
  conans/client/source.py
  conans/test/command/export_dirty_test.py
  conans/test/command/source_test.py
  conans/test/utils/tools.py
Labels: stage: review

#4039 Subsystems PATH as a list failing
  conans/client/tools/win.py
Labels: stage: review

#4044 better ConanFileReference checks
  conans/model/ref.py
  conans/test/command/info_options_test.py
  conans/test/command/install_test.py
  conans/test/command/remove_test.py
  conans/test/command/search_test.py
  conans/test/functional/create_package_test.py
  conans/test/functional/scm_test.py
  conans/test/model/ref_test.py
Labels: stage: review

#4041 Propagate all download args to get
  conans/client/tools/net.py
  conans/test/util/tools_test.py
Labels: stage: review

#3957 python requires with alias
  conans/client/graph/printer.py
  conans/client/graph/python_requires.py
  conans/client/loader.py
  conans/test/client/cmd/export_test.py
  conans/test/integration/python_build_test.py
Labels: stage: review

#4018 correct/improve/simplify makefile unit test
  conans/test/generators/make_test.py
Labels: complex: medium, component: Build, priority: high, stage: queue, whiteboard

#4043 Env var for client to (un)block API V2
  conans/client/rest/rest_client.py
Labels: stage: review

#3926 Updated Colorama to allow 0.4.0 in pip requirements
  conans/requirements.txt
Labels: stage: review

#3936 Meson build helper: add test() and install() methods
  conans/client/build/meson.py
  conans/test/build_helpers/meson_test.py
Labels: complex: low, component: Build, contributor pr, priority: high, stage: review

#4045 Print warning but ignore gitignored files optimization
  conans/client/cmd/export.py
  conans/client/source.py
  conans/client/tools/scm.py
  conans/model/scm.py
Labels: stage: review

#3898 Add `include_prerelease` and `loose` option to version range expression
  conans/client/graph/range_resolver.py
  conans/requirements.txt
  conans/test/model/version_ranges_test.py
  conans/test/unittests/__init__.py
  conans/test/unittests/client/__init__.py
  conans/test/unittests/client/graph/__init__.py
  conans/test/unittests/client/graph/test_range_resolver.py
Labels: contributor pr, stage: review

#4053 Remove brackets from valid semver
  conans/client/graph/range_resolver.py
  conans/test/unittests/client/graph/test_range_resolver.py
Labels: stage: review

#4062 loading name-version for export
  conans/client/cmd/download.py
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/loader.py
  conans/test/command/create_test.py
Labels: complex: low, priority: high, stage: review, type: feature

#4061 Assuming os_build and arch_build as settings
  conans/search/search.py
  conans/test/command/search_test.py
Labels: complex: low, contributor pr, priority: high, stage: review, type: bug

#4096 remove only_v1 parameter
  conans/server/server_launcher.py
  conans/test/integration/revisions_test.py
Labels: stage: review

#4065 range resolver don't output directly
  conans/client/conan_api.py
  conans/client/graph/graph_builder.py
  conans/client/graph/graph_manager.py
  conans/client/graph/range_resolver.py
  conans/test/model/version_ranges_test.py
  conans/test/unittests/client/graph/test_range_resolver.py
Labels: complex: low, priority: high, stage: review, type: engineering, type: feature

#4114 fix ignore_error tests
  conans/test/integration/python_build_test.py
Labels: stage: review

#4115 MSBuild crash logs
  .ci/jenkins/conf.py
  .ci/jenkins/runner.py
Labels: stage: review

#4092 Fixes ftp download when authentication is required
  conans/client/tools/net.py
  conans/test/client/tools/__init__.py
  conans/test/client/tools/net_test.py
Labels: type: bug

#3804 [-e] Allow different package layouts
  conans/client/client_cache.py
  conans/client/manifest_manager.py
  conans/client/printer.py
  conans/paths.py
  conans/paths/__init__.py
  conans/paths/package_layouts/__init__.py
  conans/paths/package_layouts/package_cache_layout.py
  conans/paths/package_layouts/package_user_layout.py
  conans/paths/simple_paths.py
  conans/server/store/disk_adapter.py
  conans/server/store/server_store.py
  conans/test/functional/package_copier_test.py
  conans/test/functional/paths_test.py
  conans/test/integration/manifest_validation_test.py
  conans/test/model/version_ranges_test.py
  conans/test/server/utils/server_launcher.py
Labels: priority: high, stage: review

#4108 Add missing tools to `conans.tools`
  conans/tools.py
Labels: stage: review

#4113 msbuild temp props in build folder
  conans/client/build/msbuild.py
  conans/test/build_helpers/msbuild_test.py
  conans/util/files.py
Labels: stage: review

#4118 simplifying diamond test for faster tests
  conans/test/command/export_path_test.py
  conans/test/command/export_test.py
  conans/test/integration/diamond_test.py
  conans/test/remote/rest_api_test.py
  conans/test/utils/cpp_test_files.py
Labels: stage: review

#4122 fixing config parser escape % in py3
  conans/client/conf/__init__.py
  conans/test/command/config_test.py
Labels: stage: review

#4119 CI new tags/schema
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/pr_tags.py
  .ci/jenkins/runner.py
  .github/PR_INCREASE_TESTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: stage: review

#4130 limit cpu_count=1 for diamond test
  conans/test/integration/diamond_test.py
  conans/test/utils/tools.py
Labels: stage: review

#4128 Better debug traces and server printing config at startup
  conans/client/cmd/build.py
  conans/client/cmd/export.py
  conans/client/cmd/uploader.py
  conans/client/conan_api.py
  conans/client/graph/graph_builder.py
  conans/client/graph/proxy.py
  conans/client/installer.py
  conans/client/packager.py
  conans/client/profile_loader.py
  conans/client/remote_manager.py
  conans/client/remover.py
  conans/client/rest/auth_manager.py
  conans/client/rest/rest_client_common.py
  conans/client/rest/rest_client_v1.py
  conans/client/rest/rest_client_v2.py
  conans/client/rest/uploader_downloader.py
  conans/client/rest/version_checker.py
  conans/server/server_launcher.py
  conans/util/tracer.py
Labels: stage: review

#4131 do not pass registry, it belongs to client_cache
  conans/client/client_cache.py
  conans/client/cmd/copy.py
  conans/client/cmd/download.py
  conans/client/cmd/search.py
  conans/client/cmd/uploader.py
  conans/client/conan_api.py
  conans/client/conan_command_output.py
  conans/client/conf/config_installer.py
  conans/client/graph/graph_binaries.py
  conans/client/graph/graph_manager.py
  conans/client/graph/proxy.py
  conans/client/installer.py
  conans/client/manager.py
  conans/client/remover.py
  conans/client/source.py
  conans/test/functional/command/config_install_test.py
  conans/test/functional/command/remote_test.py
  conans/test/functional/command/remove_test.py
  conans/test/functional/command/search_test.py
  conans/test/functional/old/download_test.py
  conans/test/functional/old/registry_test.py
  conans/test/integration/conf_default_settings_test.py
  conans/test/integration/multi_remote_test.py
  conans/test/utils/tools.py
Labels: stage: review

#4143 fix revisions in nightly
  conans/test/functional/command/info_test.py
  conans/test/functional/old/remote_checks_test.py
  conans/test/integration/revisions_test.py
  conans/test/utils/tools.py
Labels: stage: review

#4138 Fix v2 schema and refactor of client/server URLs
  .ci/jenkins/Jenkinsfile
  conans/client/rest/client_routes.py
  conans/client/rest/rest_client_common.py
  conans/client/rest/rest_client_v1.py
  conans/client/rest/rest_client_v2.py
  conans/model/rest_routes.py
  conans/server/rest/bottle_routes.py
  conans/server/rest/controllers/routes.py
  conans/server/rest/controllers/search_controller.py
  conans/server/rest/controllers/v1/conan_controller.py
  conans/server/rest/controllers/v1/delete_controller.py
  conans/server/rest/controllers/v1/search_controller.py
  conans/server/rest/controllers/v2/conan_controller.py
  conans/server/rest/controllers/v2/delete_controller.py
  conans/server/rest/controllers/v2/search_controller.py
  conans/server/server_launcher.py
Labels: stage: review

#4151 Tox launcher
  README.rst
  tox.ini
Labels: stage: review

#4153 Fix/cpu count 1 default
  conans/test/functional/command/export_test.py
  conans/test/functional/command/install_test.py
  conans/test/functional/old/conanfile_extend_test.py
  conans/test/functional/old/test_migrations.py
  conans/test/integration/basic_build_test.py
  conans/test/integration/diamond_test.py
  conans/test/integration/manifest_validation_test.py
  conans/test/utils/tools.py
Labels: stage: review

#4088 Evaluate always SCM attribute before exporting the recipe
  conans/client/cmd/export.py
  conans/test/functional/old/scm_test.py
Labels: stage: review, type: bug

#4083 config install arguments for git clone and save in config
  conans/client/conan_api.py
  conans/client/conf/config_installer.py
  conans/client/tools/scm.py
  conans/test/functional/command/config_install_test.py
  conans/test/unittests/client/conf/__init__.py
  conans/test/unittests/client/conf/config_installer.py
Labels: stage: review

#4032 Small refactor of CMake build helper class
  conans/client/build/cmake.py
  conans/client/build/cmake_flags.py
  conans/client/tools/win.py
  conans/test/unittests/util/tools_test.py
  conans/tools.py
Labels: stage: review

#4155 Feature/git scm test and style
  conans/client/conf/config_installer.py
  conans/test/functional/old/scm_test.py
  conans/test/utils/tools.py
Labels: stage: review

#4103 Remove files containing Macos meta-data
  conans/client/conan_api.py
  conans/client/tools/apple.py
  conans/client/tools/files.py
  conans/test/functional/tgz_macos_dot_files.py
  conans/test/unittests/client/tools/test_files.py
Labels: stage: review

#4156 sleeps to mitigate spurious errors in testing
  conans/test/integration/conan_test_test.py
  conans/test/integration/workspace_test.py
Labels: stage: review

#4158 Store verify_ssl argument in config install
  conans/client/conf/config_installer.py
  conans/test/functional/command/config_install_test.py
  conans/test/unittests/client/conf/config_installer_test.py
Labels: stage: review

#4159 Remove OR of generator in cmake flags
  conans/client/build/cmake_flags.py
Labels: stage: review

#4125 Always add lib targets to generated targets of cmake_find_package
  conans/client/generators/cmake_find_package.py
  conans/test/generators/cmake_find_package_test.py
Labels: complex: low, component: Build, contributor pr, priority: high, stage: review, type: bug

#4106 Management of hooks folders and naming
  conans/client/conf/config_installer.py
  conans/client/hook_manager.py
  conans/model/scm.py
  conans/test/functional/command/config_install_test.py
  conans/test/functional/command/info_test.py
  conans/test/integration/hook_test.py
  conans/test/unittests/client/hook_manager_test.py
  conans/test/utils/tools.py
Labels: stage: review

#4172 Fix config install requester for download
  conans/client/conan_api.py
  conans/test/functional/command/config_install_test.py
  conans/test/utils/tools.py
Labels: stage: review

#4186 Ordered some more tests: functional & integration
  conans/test/functional/build_helpers/cmake_configs_test.py
  conans/test/functional/build_helpers/cmake_flags_test.py
  conans/test/functional/build_helpers/cmake_folders_test.py
  conans/test/functional/build_helpers/cmake_install_package_test.py
  conans/test/functional/build_helpers/cmake_targets_test.py
  conans/test/functional/command/alias_test.py
  conans/test/functional/command/remote_verify_ssl_test.py
  conans/test/functional/conanfile/__init__.py
  conans/test/functional/conanfile/deploy_import_file_permission_test.py
  conans/test/functional/conanfile/deploy_test.py
  conans/test/functional/conanfile/imports_tests.py
  conans/test/functional/conanfile/in_local_cache_test.py
  conans/test/functional/conanfile/no_copy_source_test.py
  conans/test/functional/configuration/__init__.py
  conans/test/functional/configuration/client_certs_test.py
  conans/test/functional/configuration/default_profile_test.py
  conans/test/functional/configuration/profile_build_requires_test.py
  conans/test/functional/configuration/profile_build_requires_testing_test.py
  conans/test/functional/configuration/profile_requires_test.py
  conans/test/functional/configuration/profile_test.py
  conans/test/functional/configuration/proxies_conf_test.py
  conans/test/functional/configuration/registry_test.py
  conans/test/functional/generators/cmake_multi_test.py
  conans/test/functional/graph/__init__.py
  conans/test/functional/graph/conflict_diamond_test.py
  conans/test/functional/graph/diamond_test.py
  conans/test/functional/graph/half_diamond_test.py
  conans/test/functional/graph/loop_detection_test.py
  conans/test/functional/graph/private_deps_test.py
  conans/test/functional/graph/python_diamond_test.py
  conans/test/functional/graph/require_override_test.py
  conans/test/functional/old/path_exists_test.py
  conans/test/functional/tools/__init__.py
  conans/test/functional/tools/cpu_count_test.py
  conans/test/unittests/client/recorder/__init__.py
  conans/test/unittests/client/recorder/action_recorder_test.py
  conans/test/unittests/client/recorder/search_recorder_test.py
  conans/test/unittests/client/recorder/upload_recorder_test.py
  conans/test/unittests/client/remote_manager_test.py
  conans/test/unittests/client/util/__init__.py
  conans/test/unittests/client/util/files_test.py
Labels: stage: review

#4173 Review of Contributing guidelines and added docs and stages information
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.rst
Labels: stage: review

#4188 removed Required by: virtual
  conans/client/conan_api.py
  conans/client/graph/graph_manager.py
  conans/client/manager.py
  conans/client/printer.py
  conans/test/functional/command/info_test.py
Labels: stage: review

#4194 Less likely already in use ports for StoppableThreadBottle
  conans/test/utils/tools.py
Labels: stage: review

#4204 Feature/use env in package command
  conans/client/conan_api.py
  conans/test/functional/conan_api/package_command_test.py
Labels: contributor pr

#4210 minor cleanings
  conans/client/build/cmake.py
  conans/client/cmd/uploader.py
  conans/client/file_copier.py
  conans/client/generators/b2.py
  conans/client/generators/compiler_args.py
  conans/client/generators/json_generator.py
  conans/client/graph/proxy.py
  conans/client/installer.py
  conans/client/manager.py
  conans/client/migrations.py
  conans/client/remote_manager.py
  conans/client/rest/rest_client_common.py
  conans/client/runner.py
  conans/client/tools/apple.py
  conans/client/tools/win.py
  conans/search/search.py
  conans/test/functional/generators/cmake_paths_test.py
  conans/test/functional/generators/cmake_test.py
  conans/test/functional/generators/make_test.py
  conans/test/integration/package_id_test.py
  conans/util/windows.py
Labels: stage: review
