Repository conan-io/conan, pull requests merged in 2018-07, with the labels that each got.

#3154 fixed private binary skip
  conans/client/installer.py
Labels: in review

#3170 Feature/fix old exports sources packages
  conans/client/source.py
  conans/test/functional/merge_directories_test.py
  conans/test/integration/export_sources_test.py
Labels: in review

#3153 fixed private bugs in 1.5
  conans/client/graph/graph.py
  conans/client/graph/graph_binaries.py
  conans/client/graph/printer.py
  conans/test/integration/private_deps_test.py
Labels: in review

#3171 Release/1.5.2
  conans/__init__.py
  conans/client/graph/graph.py
  conans/client/graph/graph_binaries.py
  conans/client/graph/printer.py
  conans/client/installer.py
  conans/client/source.py
  conans/test/functional/merge_directories_test.py
  conans/test/integration/export_sources_test.py
  conans/test/integration/private_deps_test.py
Labels: in review

#3176 fixed sudo=False mode=verify calling update in SystemPackageTool
  conans/client/tools/system_pm.py
  conans/test/util/tools_test.py
Labels: in review

#3177 winsdk_version and vcvars_ver in MSBuild()
  conans/client/build/msbuild.py
  conans/client/tools/win.py
Labels: in review

#3181 - call yum update instead of yum check-update
  conans/client/tools/system_pm.py
  conans/test/util/tools_test.py
Labels: in review

#3184 Fixed typo "Forbidden"
  conans/client/rest/rest_client.py
  conans/test/command/upload_test.py
Labels: in review

#3182 added conan remote list --raw
  conans/client/command.py
  conans/client/conan_command_output.py
  conans/test/command/remote_test.py
Labels: in review

#3185 use USERPROFILE in visual_studio generator
  conans/client/generators/visualstudio.py
  conans/test/generators/visual_studio_test.py
Labels: in review

#3186 fix search and remove query
  conans/client/remote_manager.py
  conans/search/search.py
  conans/test/command/remove_test.py
  conans/test/command/search_test.py
Labels: in review

#3178 managing dirty tgzs
  conans/client/remote_manager.py
  conans/test/command/upload_test.py
Labels: in review

#3036 remove pyinstaller env from conan subprocesses
  conans/client/runner.py
Labels: contributor pr

#3195 run with environment paths
  conans/model/conan_file.py
  conans/test/functional/runner_test.py
  conans/test/integration/run_envronment_test.py
Labels: in review

#3197 Feature/unzip xz
  .ci/jenkins/conf.py
  conans/client/remote_manager.py
  conans/client/tools/files.py
  conans/server/rest/controllers/file_upload_download_controller.py
  conans/test/util/xz_test.py
Labels: in review

#3187 Added filename param to tools.get()
  conans/client/tools/net.py
  conans/test/util/tools_test.py
  conans/test/utils/tools.py
Labels: in review

#3203 Remove httpbin requests from test suite
  conans/test/util/tools_test.py
Labels: in review

#3206 stripping trailing :; from LD_LIBRARY_PATH
  conans/client/runner.py
Labels: in review

#3210 adding failing requirer
  conans/client/graph/graph_builder.py
  conans/client/graph/range_resolver.py
  conans/test/command/install_test.py
Labels: in review

#3202 Solved bugs in cmake find package generator
  conans/client/generators/cmake_find_package.py
  conans/test/generators/cmake_find_package_test.py
Labels: in review

#3212 Added conan build --test and should_test to conanfile
  conans/client/build/autotools_environment.py
  conans/client/build/cmake.py
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/manager.py
  conans/model/conan_file.py
  conans/test/build_helpers/cmake_test.py
  conans/test/command/build_test.py
  conans/test/utils/conanfile.py
Labels: in review

#3136 Add toolsets
  conans/client/conf/__init__.py
Labels: contributor pr, in review

#3220 migration ready 1.6
  conans/client/migrations.py
Labels: in review

#3219 Fixed build property in Version class
  conans/model/version.py
  conans/test/model/version_test.py
Labels: in review

#3211 fix delimiter cl
  conans/client/build/visual_environment.py
  conans/client/generators/virtualenv.py
  conans/test/generators/virtualbuildenv_test.py
  conans/test/generators/virtualenv_test.py
Labels: in review

#3218 Add FRAMEWORK_SEARCH_PATHS to xcode generator
  conans/client/generators/xcode.py
  conans/model/build_info.py
  conans/test/generators/xcode_gcc_vs_test.py
Labels: in review

#3222 Use random range for bottle ports in StoppableThreadBottle
  conans/test/util/tools_test.py
  conans/test/utils/tools.py
Labels: in review

#3160 [SCM] Capture branch and commit with `tools.Git`
  conans/client/tools/scm.py
  conans/test/util/tools_test.py
Labels: in review

#3214 fix transitive privates
  conans/client/graph/graph.py
  conans/client/graph/graph_binaries.py
  conans/test/integration/private_deps_test.py
Labels: in review

#3221 Added keep_permissions and pattern params to tools.get()
  conans/client/tools/net.py
Labels: in review

#3224 unix2dos dos2unix
  conans/client/tools/files.py
  conans/test/util/tools_test.py
Labels: in review

#3226 Feature/system requirements install
  conans/test/command/create_test.py
  conans/test/command/install_test.py
Labels: in review

#3223 fix --manifest issue with test_package
  conans/client/manager.py
  conans/test/integration/manifest_validation_test.py
Labels: bug, in review

#3229 run_environment for CMake and ld_library_path tests
  conans/client/build/cmake.py
  conans/client/tools/env.py
  conans/test/integration/conan_env_test.py
  conans/test/integration/run_envronment_test.py
Labels: in review

#3251 Bump version for PyYAML to 3.13
  conans/requirements.txt
Labels: contributor pr

#3246 Prepare for revisions
  conans/client/cmd/copy.py
  conans/client/cmd/uploader.py
  conans/client/conan_api.py
  conans/client/graph/graph_binaries.py
  conans/client/graph/graph_builder.py
  conans/client/graph/proxy.py
  conans/client/printer.py
  conans/client/recorder/action_recorder.py
  conans/client/recorder/search_recorder.py
  conans/client/remote_manager.py
  conans/client/remote_registry.py
  conans/client/remover.py
  conans/client/rest/auth_manager.py
  conans/client/rest/rest_client.py
  conans/client/rest/rest_client_common.py
  conans/client/rest/rest_client_v1.py
  conans/client/rest/rest_client_v2.py
  conans/client/rest/uploader_downloader.py
  conans/client/source.py
  conans/test/functional/registry_test.py
  conans/test/model/transitive_reqs_test.py
  conans/test/model/version_ranges_test.py
  conans/test/remote/auth_bearer_test.py
  conans/test/remote/rest_api_test.py
Labels: in review

#3257 Fixed server environment default init
  .ci/jenkins/Jenkinsfile
  conans/server/conf/__init__.py
Labels: in review

#3252 - add print_errors option to PkgConfig helper
  conans/client/tools/pkg_config.py
Labels: contributor pr

#3265 small refactor of patch_config_paths()
  conans/client/build/cmake.py
Labels: in review

#3270 Refactor remote=>remote_name
  conans/client/cmd/create.py
  conans/client/cmd/download.py
  conans/client/cmd/search.py
  conans/client/cmd/test.py
  conans/client/cmd/uploader.py
  conans/client/cmd/user.py
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/conan_command_output.py
  conans/client/graph/proxy.py
  conans/client/installer.py
  conans/client/manifest_manager.py
  conans/client/printer.py
  conans/client/recorder/action_recorder.py
  conans/client/recorder/search_recorder.py
  conans/client/remote_manager.py
  conans/client/remote_registry.py
  conans/client/remover.py
  conans/client/rest/auth_manager.py
  conans/test/command/search_test.py
  conans/test/functional/action_recorder_test.py
  conans/test/functional/registry_test.py
  conans/util/tracer.py
Labels: in review

#3272 fixing --build-order by collapsing graph
  conans/client/graph/graph.py
  conans/test/command/info_test.py
Labels: in review

#3281 forbid an alias to a different package name
  conans/client/cmd/export.py
  conans/test/integration/alias_test.py
Labels: in review

#3290 Fix download help
  conans/client/command.py
Labels: in review
