Repository conan-io/conan, pull requests merged in 2018-10, with the labels that each got.

#3615 Add environment variable CONAN_DEFAULT_PROFILE to define path to default profile
  conans/client/conf/__init__.py
  conans/client/migrations.py
  conans/test/functional/default_profile_test.py
Labels: in review

#3613 Fix trace all api calls
  conans/client/rest/conan_requester.py
  conans/client/rest/rest_client_common.py
  conans/test/functional/conan_trace_file_test.py
  conans/util/tracer.py
Labels: in review

#3646 Add bottle as dev requirement
  conans/requirements_dev.txt
Labels: in review

#3505 Feature/fix os walk py2
  conans/client/build/cmake.py
  conans/client/conf/config_installer.py
  conans/client/file_copier.py
  conans/client/source.py
  conans/client/tools/scm.py
  conans/model/manifest.py
  conans/test/functional/scm_test.py
  conans/test/util/files_test.py
  conans/util/files.py
Labels: in review

#3647 system_requirements checked always on installer
  conans/client/installer.py
  conans/test/integration/system_reqs_test.py
Labels: in review

#3545 Unzip progress bars
  conans/client/output.py
  conans/client/remote_manager.py
  conans/requirements.txt
  conans/util/progress_bar.py
Labels: in review

#3456 Feature/message alias overridden
  conans/client/graph/graph_builder.py
  conans/test/integration/alias_test.py
Labels: in review

#3675 allow relative paths (from conan.conf) in env variable
  conans/client/conf/__init__.py
  conans/test/functional/default_profile_test.py
Labels: in review

#3633 Removed output parameter from latest visual public function
  conans/client/conf/detect.py
  conans/client/tools/win.py
  conans/test/util/vcvars_clangcl_test.py
Labels: in review

#3477 Allow specifying default_options as a dictionary (close #2713)
  conans/model/conan_file.py
  conans/model/options.py
  conans/test/integration/options_test.py
  conans/test/model/options_test.py
  conans/test/model/transitive_reqs_test.py
Labels: in review

#3634 Feature/inspect
  conans/client/client_cache.py
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/printer.py
  conans/test/command/inspect_test.py
Labels: in review

#3595 Added test of how to package an Apple Framework
  conans/test/integration/cmake_targets_test.py
Labels: in review

#3599 Management of GNU installation vars in CMake and Autotools
  conans/client/build/autotools_environment.py
  conans/client/build/cmake_flags.py
  conans/test/build_helpers/autotools_configure_test.py
  conans/test/build_helpers/cmake_test.py
Labels: in review

#3680 Install config from folder
  README.rst
  conans/client/command.py
  conans/client/conf/config_installer.py
  conans/test/command/config_install_test.py
Labels: contributor pr

#3681 Feature/inspect all
  conans/client/conan_api.py
  conans/test/command/inspect_test.py
Labels: in review

#3552 fixed duplicated download of manifest and manifest download output
  conans/client/cmd/uploader.py
  conans/client/remote_manager.py
  conans/client/rest/auth_manager.py
  conans/client/rest/rest_client.py
  conans/client/rest/rest_client_common.py
  conans/client/rest/rest_client_v1.py
  conans/client/rest/uploader_downloader.py
  conans/test/remote/rest_api_test.py
Labels: in review

#3399 Fix cmake config file patching on Windows
  conans/client/build/cmake.py
  conans/client/tools/files.py
  conans/test/build_helpers/cmake_test.py
  conans/test/integration/cmake_install_package_test.py
  conans/test/util/tools_test.py
Labels: in review

#3192 Implementation of SCM feature for SVN
  .gitignore
  conans/client/cmd/export.py
  conans/client/source.py
  conans/client/tools/scm.py
  conans/model/scm.py
  conans/test/functional/scm_test.py
  conans/test/util/tools_test.py
  conans/test/utils/tools.py
Labels: in review

#3684 Fix: propagation of options with value None upstream
  conans/model/options.py
  conans/test/model/options_test.py
Labels: in review

#3685 Fix tests than were failing in py3.4
  conans/test/model/options_test.py
Labels: in review

#3686 Add seekable function to progress bar wrapper
  conans/util/progress_bar.py
Labels: in review

#3690 Feature/fix autotools flags
  conans/client/build/autotools_environment.py
  conans/test/build_helpers/autotools_configure_test.py
Labels: in review

#3703 Disable v2 for 1.8 release
  .ci/jenkins/Jenkinsfile
  conans/client/rest/rest_client.py
Labels: in review

#3706 remove warnings related to python_requires
  conans/client/cmd/export_linter.py
  conans/client/graph/python_requires.py
  conans/pylint_plugin.py
  conans/test/command/export_linter_test.py
Labels: in review

#3710 Feature/rename docker images
  conans/client/cmd/new_ci.py
  conans/test/command/new_test.py
Labels: in review

#3692 fix raise without Exception
  conans/test/utils/tools.py
Labels: in review

#3715 Fix AutoTools flags --sbindir and --libexecdir
  conans/client/build/autotools_environment.py
  conans/test/build_helpers/autotools_configure_test.py
Labels: in review

#3718 Fix misleading warning message in tools.collect_libs()
  conans/client/tools/files.py
  conans/model/conan_file.py
  conans/test/util/tools_test.py
Labels: in review

#3691 pep8
  conans/client/build/autotools_environment.py
  conans/client/build/cmake.py
  conans/client/build/cmake_flags.py
  conans/client/conan_api.py
  conans/client/manager.py
Labels: in review

#3676 Registry internal refactor + json file
  conans/client/client_cache.py
  conans/client/cmd/download.py
  conans/client/cmd/search.py
  conans/client/cmd/uploader.py
  conans/client/conan_api.py
  conans/client/conf/config_installer.py
  conans/client/graph/graph_binaries.py
  conans/client/graph/proxy.py
  conans/client/installer.py
  conans/client/printer.py
  conans/client/remote_registry.py
  conans/client/remover.py
  conans/client/source.py
  conans/test/command/config_install_test.py
  conans/test/command/info_folders_test.py
  conans/test/command/info_test.py
  conans/test/command/remote_test.py
  conans/test/command/upload_test.py
  conans/test/functional/registry_test.py
  conans/test/utils/tools.py
Labels: in review

#3747 yum update without confirmation.
  conans/client/tools/system_pm.py
  conans/test/util/tools_test.py
Labels: contributor pr

#3727 Add --askpass argument to 'sudo' if it is not an interactive terminal
  conans/client/runner.py
  conans/client/tools/system_pm.py
  conans/test/util/tools_test.py
Labels: in review

#3758 Enable "unhack" user and channel
  conans/model/conan_file.py
  conans/test/integration/same_userchannel_test.py
Labels: in review

#3750 AST parsing in python 2 with encoding and shebang
  conans/client/cmd/export.py
  conans/test/client/cmd/ast_replacement_scm_test.py
Labels: in review

#3763 Up tqdm to 4.27: fix weakref warning
  conans/requirements.txt
Labels: in review

#3772 fix import
  conans/test/client/cmd/ast_replacement_scm_test.py
Labels: in review

#3781 fix typo
  conans/client/command.py
Labels: in review

#3726 Binary registry
  conans/client/client_cache.py
  conans/client/cmd/export.py
  conans/client/cmd/uploader.py
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/graph/graph_binaries.py
  conans/client/installer.py
  conans/client/remote_registry.py
  conans/test/command/remote_test.py
  conans/test/command/upload_complete_test.py
  conans/test/functional/registry_test.py
  conans/test/integration/devflow_test.py
  conans/test/integration/install_update_test.py
  conans/test/remote_checks_test.py
  conans/test/utils/tools.py
Labels: in review

#3780 renamed and moved test
  conans/test/functional/scm_nested_subfolder_test.py
Labels: in review

#3717 Show cpp_info in output from install and create commands
  conans/client/installer.py
  conans/client/recorder/action_recorder.py
  conans/test/command/json_output_test.py
Labels: in review

#3789 Test SCM with nested subfolders
  conans/test/functional/scm_nested_subfolder_test.py
  conans/test/functional/scm_test.py
Labels: engineering, in review

#3768 using profile or settings in export-pkg allowed
  conans/client/conan_api.py
  conans/client/packager.py
  conans/test/command/export_pkg_test.py
Labels: in review

#3779 refactor, removing things from manager
  conans/client/cmd/build.py
  conans/client/cmd/export_pkg.py
  conans/client/cmd/test.py
  conans/client/conan_api.py
  conans/client/manager.py
  conans/test/command/upload_complete_test.py
  conans/test/functional/create_package_test.py
Labels: in review

#3801 Manifest diff prints
  conans/client/cmd/uploader.py
  conans/model/manifest.py
  conans/test/command/upload_test.py
Labels: in review

#3795 new test for conditional requirements keep package_id
  conans/test/conditional_requirements_id_test.py
Labels: in review

#3757 Handle old versions (<1.8) of SVN
  conans/client/tools/scm.py
  conans/test/util/tools_test.py
  conans/test/utils/tools.py
Labels: enhancement, in review

#3751 Feature: Premake generator
  conans/client/generators/__init__.py
  conans/client/generators/premake.py
  conans/paths.py
  conans/test/generators/premake_test.py
Labels: contributor pr

#3554 Improve "conanfile not found" message
  conans/client/conan_api.py
  conans/test/command/package_test.py
  conans/test/command/source_test.py
  conans/test/command/test_package_test.py
Labels: contributor pr

#3701 Fix a typo in "CircleCI"
  conans/client/command.py
Labels: contributor pr

#3806 implement download concurrency checks
  conans/client/graph/graph_binaries.py
  conans/client/installer.py
Labels: in review

#3803 Fix: use self._run instead of self._conanfile.run to ensure vcvars apply for Ninja/NMake generators
  conans/client/build/cmake.py
  conans/test/build_helpers/cmake_test.py
Labels: contributor pr

#3782 adding test for transitive options not affecting binary ID
  conans/test/transitive_options_affect_id_test.py
Labels: in review

#3825 Feature/refactors graph load
  conans/client/conan_api.py
  conans/client/graph/graph.py
  conans/client/graph/graph_builder.py
  conans/client/graph/graph_manager.py
  conans/client/manager.py
  conans/test/model/fake_retriever.py
  conans/test/model/version_ranges_test.py
Labels: in review

#3837 Fix loader
  conans/client/loader.py
Labels: in review

#3841 Issue/3714 default profile arch
  conans/client/conf/detect.py
  conans/test/util/detect_test.py
Labels: in review

#3839 Do not ask for username if it is already given
  conans/client/userio.py
  conans/test/client/userio.py
Labels: in review

#3838 Don't touch registry when deleted from a remote
  conans/client/remover.py
  conans/test/command/remote_test.py
Labels: in review

#3748 Test and fix for read only files from `svn:needs-lock` attribute (#3638)
  conans/client/cmd/export.py
  conans/client/source.py
  conans/test/functional/scm_test.py
  conans/test/utils/tools.py
Labels: contributor pr

#3843 Do not allow wildcards in 'conan download' command
  conans/client/cmd/uploader.py
  conans/client/conan_api.py
  conans/model/ref.py
  conans/test/command/download_test.py
  conans/test/model/ref_test.py
Labels: in review

#3702 #3671 Add attribute tags
  conans/client/cmd/new.py
  conans/client/conan_api.py
  conans/client/graph/grapher.py
  conans/client/printer.py
  conans/model/conan_file.py
  conans/test/command/info_test.py
  conans/test/command/inspect_test.py
  conans/test/command/new_test.py
Labels: contributor pr

#3816 Check for UnicodeEncodeError when reading .count-file
  conans/util/locks.py
Labels: in review

#3845 Add neon as linux distro for SystemPackageTools
  conans/client/tools/oss.py
  conans/test/util/tools_test.py
Labels: in review

#3847 Feature/remove warning lock
  conans/test/functional/package_integrity_test.py
  conans/util/locks.py
Labels: in review

#3852 Fix develop tests
  conans/test/integration/alias_test.py
Labels: in review

#3854 reverting imported modules management
  conans/client/loader.py
  conans/test/functional/conanfile_helpers_test.py
Labels: in review

#3836 Do not modify slashes on env variables (EnvValues)
  conans/client/loader.py
  conans/model/env_info.py
  conans/test/generators/virtualenv_test.py
Labels: Feedback please!, in review

#3834 failed builds dirty checks
  conans/client/installer.py
  conans/test/integration/build_id_test.py
Labels: in review

#3791 Fix: fix link_flags management with MSBuild
  conans/client/build/visual_environment.py
  conans/test/build_helpers/visual_environment_test.py
Labels: contributor pr

#3832 Fix: call vcvars for clang-cl as well
  conans/client/build/cmake.py
  conans/test/build_helpers/cmake_test.py
Labels: contributor pr

#3849 Revert "Test and fix for read only files from `svn:needs-lock`attribute"
  conans/client/cmd/export.py
  conans/client/source.py
  conans/test/functional/scm_test.py
  conans/test/utils/tools.py
Labels: in review

#3844 fixing error with custom compiler and cppstd
  conans/client/build/cppstd_flags.py
  conans/client/settings_preprocessor.py
  conans/test/integration/cppstd_test.py
  conans/test/model/other_settings_test.py
Labels: in review

#3820 Test conan_sources.tgz is deleted when using SCM feature
  conans/test/client/cmd/export_test.py
Labels: in review

#3830 ignore line if it is empty
  conans/client/tools/scm.py
Labels: in review

#3643 - use major-only for Clang >= 8.0
  conans/client/cmd/new_ci.py
  conans/client/conf/__init__.py
  conans/client/conf/detect.py
  conans/client/generators/cmake_common.py
  conans/test/build_helpers/cpp_std_flags_test.py
Labels: in review

#3850 Feature/improve upload recorder
  conans/client/cmd/uploader.py
  conans/client/recorder/upload_recoder.py
  conans/test/functional/upload_recorder_test.py
Labels: in review

#3651 #3649 Update CI templates
  conans/client/cmd/new_ci.py
  conans/test/command/new_test.py
Labels: in review

#3860 Excluded build type flags for MSBuild()
  conans/client/build/msbuild.py
  conans/client/build/visual_environment.py
  conans/test/build_helpers/msbuild_test.py
  conans/test/util/build_sln_command_test.py
Labels: in review

#3661 Feature/reuse python requires exports
  conans/client/cmd/export.py
  conans/client/conan_api.py
  conans/client/graph/printer.py
  conans/client/graph/python_requires.py
  conans/client/installer.py
  conans/client/loader.py
  conans/client/source.py
  conans/test/integration/python_build_test.py
Labels: in review

#3861 Hide conaninfo download for manifest checks
  conans/__init__.py
  conans/client/rest/rest_client_v1.py
  conans/test/integration/install_update_test.py
  conans/test/remote/broken_download_test.py
Labels: in review

#3865 Update gcc version in allowed settings to 8.2
  conans/client/conf/__init__.py
Labels: contributor pr

#3857 Feature/srcdirs
  conans/client/generators/cmake.py
  conans/client/generators/cmake_common.py
  conans/model/build_info.py
  conans/test/generators/cmake_test.py
  conans/test/generators/generators_test.py
  conans/test/integration/cmake_flags_test.py
Labels: in review

#3809 Added --json output to conan export_pkg command
  conans/client/cmd/export_pkg.py
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/recorder/action_recorder.py
  conans/test/command/export_pkg_test.py
  conans/test/command/json_output_test.py
  conans/test/functional/action_recorder_test.py
Labels: in review

#3653 Use XML output to compute SVN.is_pristine()
  conans/client/tools/scm.py
  conans/test/util/tools_test.py
Labels: enhancement, in review

#3867 Rename Plugins as Hooks
  conans/client/client_cache.py
  conans/client/cmd/build.py
  conans/client/cmd/download.py
  conans/client/cmd/export.py
  conans/client/cmd/export_pkg.py
  conans/client/cmd/test.py
  conans/client/cmd/uploader.py
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/conf/__init__.py
  conans/client/hook_manager.py
  conans/client/installer.py
  conans/client/manager.py
  conans/client/migrations.py
  conans/client/packager.py
  conans/client/plugin_manager.py
  conans/client/recorder/search_recorder.py
  conans/client/recorder/upload_recoder.py
  conans/client/remote_manager.py
  conans/client/source.py
  conans/test/command/info_test.py
  conans/test/functional/create_package_test.py
  conans/test/functional/hook_manager_test.py
  conans/test/integration/hook_test.py
  conans/test/test_migration_default_profile.py
  conans/test/test_migrations.py
  conans/test/utils/tools.py
Labels: in review

#3870 Test plugins->hooks migration with an already hooks folder
  conans/client/migrations.py
  conans/test/test_migrations.py
Labels: in review

#3869 Convert paths for known compilation env vars
  conans/client/tools/win.py
Labels: in review

#3871 Tag tests related to SVN (and a couple using Git)
  conans/test/functional/scm_test.py
  conans/test/util/tools_test.py
Labels: in review

#3879 Servers with order guaranteed in testing
  conans/test/command/download_test.py
  conans/test/command/search_test.py
  conans/test/command/user_test.py
  conans/test/integration/install_update_test.py
  conans/test/integration/test_build_info_extraction.py
  conans/test/integration/version_ranges_diamond_test.py
  conans/test/remote_checks_test.py
  conans/test/utils/tools.py
Labels: in review

#3876 Feature/fix python requires imports
  conans/client/graph/python_requires.py
  conans/client/loader.py
  conans/test/client/cmd/export_test.py
  conans/test/functional/scm_test.py
  conans/test/integration/python_build_test.py
  conans/test/util/tools_test.py
Labels: in review

#3878 Travis CI fixes
  .travis.yml
Labels: contributor pr

#3885 Make option --askpass compatible with sudo version 1.8.7 or older.
  conans/client/tools/system_pm.py
  conans/test/util/tools_test.py
Labels: in review

#3890 Hotfix/fix prefs remove
  conans/client/graph/graph_binaries.py
  conans/client/remover.py
  conans/test/command/remove_test.py
  conans/test/integration/multi_remote_test.py
Labels: in review

#3888 Replaced settings-less package_id with a constant
  conans/test/build_helpers/autotools_configure_test.py
  conans/test/command/build_test.py
  conans/test/command/conan_get_test.py
  conans/test/command/export_pkg_test.py
  conans/test/command/info_folders_test.py
  conans/test/command/remote_test.py
  conans/test/command/remove_test.py
  conans/test/command/test_package_test.py
  conans/test/command/upload_complete_test.py
  conans/test/command/upload_test.py
  conans/test/conditional_requirements_id_test.py
  conans/test/functional/default_profile_test.py
  conans/test/functional/package_id_test.py
  conans/test/functional/path_limit_test.py
  conans/test/functional/read_only_test.py
  conans/test/functional/scm_test.py
  conans/test/functional/short_paths_test.py
  conans/test/generators/generator_filter_error_test.py
  conans/test/generators/generators_test.py
  conans/test/integration/conan_test_test.py
  conans/test/integration/export_sources_test.py
  conans/test/integration/hook_test.py
  conans/test/integration/install_update_test.py
  conans/test/integration/manifest_validation_test.py
  conans/test/integration/multi_remote_test.py
  conans/test/integration/options_test.py
  conans/test/integration/private_deps_test.py
  conans/test/integration/python_build_test.py
  conans/test/integration/symlinks_test.py
  conans/test/integration/system_reqs_test.py
  conans/test/integration/version_ranges_diamond_test.py
  conans/test/model/transitive_reqs_test.py
  conans/test/remote_checks_test.py
  conans/test/util/xz_test.py
  conans/test/utils/tools.py
Labels: in review
