Repository conan-io/conan, pull requests merged in 2018-11, with the labels that each got.

#3905 remove search from download call
  conans/client/cmd/download.py
  conans/client/conan_api.py
  conans/client/store/localdb.py
  conans/client/userio.py
  conans/test/integration/install_selected_packages_test.py
Labels: in review

#3908 Fix topics breaking info graph html
  conans/client/graph/grapher.py
  conans/test/command/info_test.py
  conans/test/command/inspect_test.py
Labels: in review

#3918 vcvars regression
  conans/client/tools/win.py
  conans/test/util/vcvars_arch_test.py
Labels: in review

#3954 SVN api changes happended in version 1.9
  conans/client/tools/scm.py
Labels: stage: review

#3976 fix compiler args
  conans/client/build/compiler_flags.py
  conans/test/generators/compiler_args_test.py
Labels: stage: review

#3981 Test to ensure the version ranges behavior
  conans/test/integration/version_ranges_diamond_test.py
Labels: stage: review

#4000 dev packages
  .ci/bump_dev_version.py
  .ci/jenkins/Jenkinsfile
Labels: stage: review

#4006 README for dev packages
  README.rst
Labels: stage: review

#4012 mkdir fails when the directory exists
  conans/util/files.py
Labels: stage: review

#3991 Fixed linker flags
  conans/client/generators/qbs.py
Labels: stage: triaging

#3914 Inspect settings and options (#3883)
  conans/client/conan_api.py
  conans/client/printer.py
  conans/model/conan_file.py
  conans/test/command/inspect_test.py
Labels: stage: review

#3907 Pass arguments 'output' and 'requester' to every function that uses them
  conans/client/build/autotools_environment.py
  conans/client/build/cmake.py
  conans/client/build/cmake_flags.py
  conans/client/build/compiler_flags.py
  conans/client/build/msbuild.py
  conans/client/build/visual_environment.py
  conans/client/conan_api.py
  conans/client/conf/config_installer.py
  conans/client/migrations.py
  conans/client/tools/net.py
  conans/test/build_helpers/autotools_configure_test.py
  conans/test/build_helpers/cmake_test.py
  conans/test/build_helpers/visual_environment_test.py
  conans/test/command/package_test.py
  conans/test/integration/alias_test.py
  conans/test/integration/devflow_test.py
  conans/test/integration/profile_test.py
  conans/test/integration/workspace_test.py
  conans/test/test_migrations.py
  conans/test/util/build_sln_command_test.py
  conans/test/util/conanfile_tools_test.py
  conans/test/util/files_extract_wildcard_test.py
  conans/test/util/tools_test.py
  conans/test/util/xz_test.py
  conans/test/util/zip_permissions_test.py
Labels: stage: review, type: feature

#4003 Adds Make generator
  conans/client/generators/__init__.py
  conans/client/generators/make.py
  conans/client/generators/premake.py
  conans/paths.py
  conans/test/generators/make_test.py
Labels: stage: review

#3626 Added the ability to output a binary log from MSBuild.
  conans/client/build/msbuild.py
  conans/test/build_helpers/msbuild_test.py
Labels: stage: review

#4024 Improve CMake helper in_local_cache assignation
  conans/client/build/cmake_flags.py
Labels: stage: review
