Repository conan-io/conan, pull requests merged in 2018-02, with the labels that each got.

#2450 fix encode-errors in vswhere output
  conans/client/tools/win.py
Labels: [in review], bug

#2447 Implements #2420 : --update option should not ignore local packages
  conans/client/manager.py
  conans/client/require_resolver.py
  conans/test/integration/version_range_error_test.py
  conans/test/integration/version_ranges_conflict_test.py
  conans/test/integration/version_ranges_diamond_test.py
  conans/test/model/version_ranges_test.py
Labels: [in review]

#2448 Not 0 exit code when handling signals.
  conans/client/command.py
Labels: [in review]

#2452 Don't display credentials from url while conan config install
  conans/client/conf/config_installer.py
  conans/test/command/config_install_test.py
Labels: [in review]

#2443 Feature/fix develop bug
  conans/client/manager.py
  conans/test/command/create_test.py
  conans/test/functional/develop_test.py
Labels: [in review], bug

#2459 Reload client_cache after calling conan.config_rm()
  conans/client/client_cache.py
  conans/client/conan_api.py
  conans/test/conan_api/config.py
Labels: [in review]

#2468 Add --verify-ssl parameter to conan config install
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/conf/config_installer.py
  conans/test/command/config_install_test.py
Labels: [in review]

#2458 Feature/cmake arch fi
  conans/client/build/autotools_environment.py
  conans/client/build/cmake.py
  conans/client/build/compiler_flags.py
  conans/client/build/visual_environment.py
  conans/client/generators/__init__.py
  conans/client/generators/cmake_multi.py
  conans/client/generators/compiler_args.py
  conans/client/generators/gcc.py
  conans/client/tools/__init__.py
  conans/paths.py
  conans/test/build_helpers/autotools_configure_test.py
  conans/test/build_helpers/cmake_test.py
  conans/test/build_helpers/compiler_flags_test.py
  conans/test/generators/compiler_args_test.py
Labels: [in review]

#2473 adding new help command
  conans/client/command.py
  conans/test/command/help_test.py
Labels: [in review]

#2477 adding information to ResourceCompile VS generator
  conans/client/generators/visualstudio.py
Labels: [in review]

#2483 Removed conan-transit from default registry
  conans/client/remote_registry.py
  conans/test/functional/registry_test.py
Labels: [in review]

#2489 Add GCC 5.5 to default configuration
  conans/client/conf/__init__.py
Labels: [in review]

#2395 Add build_requires support for conanfile.txt loader
  conans/client/loader.py
  conans/client/loader_parse.py
  conans/test/functional/conanfile_loader_test.py
  conans/test/integration/build_requires_test.py
Labels: [in review], enhancement

#2496 Feature/minor cleanups
  conans/client/build_requires.py
  conans/client/client_cache.py
  conans/client/command.py
  conans/client/remote_registry.py
Labels: in review

#2495 Added keep_path parameter to copy in imports()
  conans/client/importer.py
  conans/client/loader_parse.py
  conans/test/functional/conanfile_loader_test.py
  conans/test/functional/imports_tests.py
Labels: in review

#2478 - change PkgConfig helper to fail as early as possible
  conans/client/tools/pkg_config.py
  conans/test/util/pkg_config_test.py
Labels: in review

#2504 Feature/server relative urls
  conans/client/rest/rest_client.py
  conans/server/conf/__init__.py
  conans/test/integration/complete_test.py
  conans/test/remote/rest_api_test.py
  conans/test/server/conan_server_config_parser_test.py
  conans/test/server/conf_test.py
  conans/test/utils/tools.py
Labels: in review

#2404 Improved tools.vs_installation_path() with compiler preference
  conans/client/conf/__init__.py
  conans/client/tools/win.py
  conans/test/util/tools_test.py
  conans/util/env_reader.py
Labels: in review

#2506 build_type not defined not error
  conans/client/loader.py
  conans/test/built_type_setting_test.py
Labels: in review

#2486 cppstd setting at first level
  conans/client/build/autotools_environment.py
  conans/client/build/cmake.py
  conans/client/build/cppstd_flags.py
  conans/client/build/visual_environment.py
  conans/client/conf/__init__.py
  conans/client/generators/cmake_common.py
  conans/client/generators/compiler_args.py
  conans/client/migrations.py
  conans/client/settings_preprocessor.py
  conans/model/info.py
  conans/test/build_helpers/autotools_configure_test.py
  conans/test/build_helpers/cpp_std_flags_test.py
  conans/test/build_helpers/msbuild_test.py
  conans/test/generators/cmake_test.py
  conans/test/integration/cmake_flags_test.py
  conans/test/integration/cppstd_test.py
  conans/test/integration/package_id_test.py
  conans/test/utils/visual_project_files.py
Labels: in review

#2214 Delete build folder after successful conan test (#2160)
  conans/client/cmd/test.py
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/conf/__init__.py
  conans/test/command/create_test.py
  conans/test/command/test_package_test.py
Labels: in review

#2510 Package ID in the missing msg
  conans/client/installer.py
  conans/test/integration/package_id_test.py
Labels: in review

#2493 2332 system requirements optional
  conans/client/conf/__init__.py
  conans/client/tools/system_pm.py
  conans/test/util/tools_test.py
Labels: in review

#2518 set develop=True for export-pkg
  conans/client/manager.py
  conans/test/command/export_pkg_test.py
Labels: in review

#2343 function to patch cmake export modules for portability
  conans/client/build/cmake.py
  conans/test/build_helpers/cmake_test.py
  conans/test/integration/cmake_install_package_test.py
Labels: in review

#2529 Feature/skip sln project upgrade
  conans/client/conf/__init__.py
  conans/client/tools/win.py
  conans/test/build_helpers/msbuild_test.py
  conans/test/util/build_sln_command_test.py
Labels: in review

#2525 disabling cmake compiler check for unknown compilers
  conans/client/generators/cmake_common.py
Labels: in review

#2533 adding user and channel to test_package/conanfile
  conans/__init__.py
  conans/client/cmd/test.py
  conans/client/manager.py
  conans/test/integration/same_userchannel_test.py
Labels: in review
