Repository conan-io/conan, pull requests merged in 2018-03, with the labels that each got.

#2540 Not eabi for x86
  conans/client/build/autotools_environment.py
  conans/test/build_helpers/autotools_configure_test.py
Labels: in review

#2550 Clean env var user for testing
  .ci/jenkins/runner.py
Labels: in review

#2546 output errors for invalid platforms
  conans/client/build/msbuild.py
  conans/client/tools/win.py
  conans/test/util/build_sln_command_test.py
Labels: in review

#2549 Switch from nose-parameterized to parameterized
  conans/requirements_dev.txt
  conans/test/command/create_test.py
  conans/test/command/export_pkg_test.py
  conans/test/command/export_test.py
  conans/test/command/package_test.py
  conans/test/conan_api/manifests_arguments_test.py
  conans/test/functional/deploy_test.py
  conans/test/functional/develop_test.py
  conans/test/generators/visual_studio_multi_test.py
  conans/test/integration/build_id_test.py
  conans/test/integration/build_requires_test.py
  conans/test/integration/cmake_folders_test.py
  conans/test/integration/complete_test.py
  conans/test/integration/export_sources_test.py
  conans/test/integration/manifest_validation_test.py
  conans/test/integration/profile_test.py
  conans/test/integration/version_ranges_diamond_test.py
  conans/test/model/version_ranges_test.py
  conans/test/util/conanfile_tools_test.py
Labels: contributor pr

#2561 fix profile update for env-vars
  conans/client/cmd/profile.py
  conans/model/env_info.py
  conans/test/command/profile_test.py
Labels: in review

#2557 add --package-folder to export-pkg
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/manager.py
  conans/client/packager.py
  conans/test/command/export_pkg_test.py
Labels: in review

#2515 Add a json generator
  conans/client/generators/__init__.py
  conans/client/generators/json_generator.py
  conans/test/generators/json_test.py
  conans/test/integration/json_generator_test.py
Labels: in review

#2565 fix abs paths for json generator
  conans/client/generators/json_generator.py
  conans/test/generators/json_test.py
  conans/test/integration/json_generator_test.py
Labels: in review

#2591 Update clang version to 6.0
  conans/client/conf/__init__.py
Labels: contributor pr

#2592 fixed bug in search pkg-ref output
  conans/client/cmd/search.py
  conans/test/command/search_test.py
Labels: in review

#2519 Generate conan json dependencies for Ycm generator
  conans/client/generators/ycm.py
  conans/test/generators/generators_test.py
Labels: in review

#2570 disabling pylint for pyinstaller
  conans/client/cmd/export_linter.py
Labels: in review

#2577 Feature/installer refactor
  conans/client/importer.py
  conans/client/installer.py
  conans/client/manager.py
  conans/test/command/imports_test.py
Labels: in review

#2599 Fixed copy_deps linter warning when exporting
  conans/client/cmd/export_linter.py
  conans/model/conan_file.py
  conans/test/command/export_linter_test.py
Labels: in review

#2614 Bug printing to StringIO in python2
  conans/client/runner.py
  conans/test/functional/runner_test.py
Labels: in review

#2608 no-op if not Windows in tools.vcvars()
  conans/client/tools/win.py
  conans/test/util/tools_test.py
Labels: in review

#2600 implemented build() stages arguments
  conans/client/build/autotools_environment.py
  conans/client/build/cmake.py
  conans/client/build/meson.py
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/manager.py
  conans/model/conan_file.py
  conans/test/build_helpers/autotools_configure_test.py
  conans/test/build_helpers/cmake_test.py
  conans/test/build_helpers/meson_test.py
  conans/test/command/build_test.py
  conans/test/utils/conanfile.py
Labels: in review

#2581 Feature/client certificates
  conans/client/client_cache.py
  conans/client/conan_api.py
  conans/client/conf/__init__.py
  conans/client/rest/cacert.py
  conans/client/rest/conan_requester.py
  conans/client/rest/rest_client.py
  conans/client/rest/version_checker.py
  conans/client/tools/net.py
  conans/paths.py
  conans/test/command/conan_get_test.py
  conans/test/command/config_install_test.py
  conans/test/functional/client_certs_test.py
  conans/test/functional/proxies_conf_test.py
  conans/test/functional/verify_ssl_test.py
  conans/test/remote/put_properties_test.py
  conans/test/remote/rest_api_test.py
  conans/test/util/build_sln_command_test.py
  conans/test/utils/tools.py
  conans/tools.py
Labels: in review

#2602 Refactor triplets GNU autotools
  conans/client/build/autotools_environment.py
  conans/client/tools/oss.py
  conans/test/build_helpers/autotools_configure_test.py
  conans/test/utils/conanfile.py
Labels: in review

#2622 make conan download directly retrieve the sources
  conans/client/manager.py
  conans/test/command/download_test.py
Labels: in review

#2624 doing an exports while conan-source
  conans/client/manager.py
  conans/test/command/source_test.py
Labels: in review

#2563 CONAN_USER_HOME_SHORT cygwin/msys2 access problems
  conans/test/command/info_folders_test.py
  conans/util/windows.py
Labels: in review

#2637 Better output if recipe found but not the package
  conans/client/printer.py
  conans/test/integration/private_deps_test.py
Labels: in review

#2640 Added test reusing ConanFile from python file
  conans/test/conanfile_extend_test.py
Labels: in review

#2642 Feature/fix cacert and clean package
  conans/client/installer.py
  conans/client/rest/cacert.py
Labels: in review

#2634 conan download --recipe param and test
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/manager.py
  conans/test/command/download_test.py
Labels: in review

#2633 conan install parser nargs changed to ? and addded tests
  conans/client/command.py
  conans/test/command/install_test.py
Labels: in review

#2639 2290 show users for given remote
  conans/client/manager.py
  conans/client/proxy.py
  conans/test/command/user_test.py
Labels: in review

#2611 Feature/pylint_external
  .ci/jenkins/runner.py
  conans/client/build/compiler_flags.py
  conans/client/cmd/export_linter.py
  conans/client/tools/oss.py
  conans/test/command/export_linter_test.py
  pyinstaller.py
Labels: in review

#2646 fix cppstd defaults for clang 6.0 + fix bug with defaults
  conans/client/build/cppstd_flags.py
  conans/test/build_helpers/cpp_std_flags_test.py
Labels: in review

#2653 Feature/msbuild improved
  conans/client/build/msbuild.py
  conans/client/build/visual_environment.py
  conans/client/cmd/export.py
  conans/client/cmd/export_linter.py
  conans/client/tools/files.py
  conans/client/tools/win.py
  conans/requirements.txt
  conans/test/build_helpers/msbuild_test.py
  conans/test/command/export_linter_test.py
  conans/test/util/build_sln_command_test.py
  conans/test/util/tools_test.py
  conans/util/files.py
Labels: in review

#2656 raise error if git clone fails in conan-config-install
  conans/client/conan_api.py
  conans/client/conf/config_installer.py
  conans/client/runner.py
  conans/test/command/config_install_test.py
Labels: bug, in review

#2597 Fixing diamonds with alias
  conans/client/deps_builder.py
  conans/test/integration/alias_test.py
  conans/test/model/transitive_reqs_test.py
Labels: in review

#2555 Add escapes to CMake generator for cpp_info variables
  conans/client/generators/cmake.py
  conans/test/generators/cmake_test.py
Labels: in review

#2659 added pythonpath to package_info() call
  conans/client/installer.py
  conans/client/tools/env.py
  conans/model/env_info.py
  conans/test/integration/python_build_test.py
Labels: in review

#2662 cmake escape integration test
  conans/test/integration/cmake_flags_test.py
Labels: in review

#2668 Preliminary support for disabling login prompt (#2502)
  conans/client/conf/__init__.py
  conans/client/rest/auth_manager.py
  conans/test/command/upload_test.py
  conans/test/command/user_test.py
Labels: contributor pr

#2669 Preliminary support for writable files from deploy and imports (#2441)
  conans/client/importer.py
  conans/test/functional/deploy_import_file_permission_test.py
Labels: in review

#2674 Fix disable login prompt environment variable.
  conans/client/rest/auth_manager.py
Labels: contributor pr

#2679 Make conanfile templates PEP8 compliant and added ConanFile docstrings
  conans/client/cmd/new.py
  conans/model/conan_file.py
Labels: in review

#2672 Add flag to avoid overwriting uploaded packages
  conans/client/cmd/uploader.py
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/proxy.py
  conans/client/remote_manager.py
  conans/client/rest/auth_manager.py
  conans/client/rest/rest_client.py
  conans/test/command/upload_test.py
  conans/test/remote/rest_api_test.py
Labels: in review

#2665 improved messages, fix manifest exceptions
  conans/client/installer.py
  conans/client/manifest_manager.py
  conans/errors.py
Labels: in review

#2652 refactoring authenticate
  conans/client/cmd/user.py
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/conf/__init__.py
  conans/client/manager.py
  conans/client/proxy.py
  conans/client/remote_manager.py
  conans/client/rest/auth_manager.py
  conans/client/userio.py
  conans/test/command/info_folders_test.py
  conans/test/command/upload_test.py
  conans/test/command/user_test.py
  conans/test/functional/conan_trace_file_test.py
  conans/test/utils/tools.py
  conans/util/tracer.py
  conans/util/windows.py
Labels: in review

#2682 Fix CONAN_CMAKE_SYSTEM_PROCESSOR
  conans/client/build/cmake.py
  conans/test/build_helpers/cmake_test.py
Labels: in review

#2654 Feature/install output
  conans/client/action_recorder.py
  conans/client/cmd/copy.py
  conans/client/cmd/uploader.py
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/conan_command_output.py
  conans/client/installer.py
  conans/client/manager.py
  conans/client/proxy.py
  conans/client/remote_manager.py
  conans/test/command/json_output_test.py
  conans/test/download_test.py
  conans/test/util/action_recorder_test.py
  conans/test/utils/tools.py
Labels: in review

#2686 json times in iso
  conans/client/action_recorder.py
  conans/client/conan_command_output.py
  conans/test/command/json_output_test.py
Labels: in review

#2685 fixing py34 pylint
  conans/client/cmd/export_linter.py
Labels: in review

#2688 fixed py34 test (order output)
  conans/test/command/user_test.py
Labels: in review
