Repository conan-io/conan, pull requests merged in 2018-05, with the labels that each got.

#2844 Feature/fix delete packageid
  conans/model/options.py
  conans/test/functional/package_id_test.py
Labels: in review

#2843 restored the save() method with append argument, broken API
  conans/test/util/conanfile_tools_test.py
  conans/tools.py
Labels: in review

#2846 fixed bash path with spaces issue
  conans/client/runner.py
  conans/client/tools/win.py
  conans/model/conan_file.py
  conans/test/util/tools_test.py
Labels: in review

#2847 Feature/2756
  conans/client/generators/pkg_config.py
  conans/test/generators/pkg_config_test.py
  conans/test/util/pkg_config_test.py
Labels: in review

#2845 Feature/fix unknown arch triplet
  conans/client/build/autotools_environment.py
  conans/client/tools/oss.py
Labels: in review

#2852 updated apple-clang in ci scripts
  conans/client/cmd/new_ci.py
Labels: in review

#2859 fix VisualStudioBuildEnvironment build type flags with toolset
  conans/client/build/compiler_flags.py
  conans/test/build_helpers/visual_environment_test.py
Labels: in review

#2853 checking tgz checksum
  conans/client/remote_manager.py
  conans/test/functional/tgz_md5_test.py
Labels: in review

#2868 Fixed VisualStudioBuildEnvironment flags in MSBuild during props template generation
  conans/client/build/msbuild.py
  conans/test/build_helpers/msbuild_test.py
Labels: in review

#2836 refactor for remove and manifests
  conans/client/client_cache.py
  conans/client/conan_api.py
  conans/client/manager.py
  conans/client/manifest_manager.py
  conans/client/proxy.py
  conans/client/remover.py
  conans/paths.py
  conans/test/command/export_path_test.py
  conans/test/command/export_test.py
  conans/test/command/remove_test.py
  conans/test/command/upload_complete_test.py
  conans/test/integration/install_update_test.py
  conans/test/integration/manifest_validation_test.py
  conans/test/integration/syncronize_test.py
  conans/test/integration/version_ranges_diamond_test.py
Labels: in review

#2876 fixing some unicode
  conans/test/util/tools_test.py
  conans/util/files.py
Labels: in review

#2884 CMAKE_SYSTEM_VERSION following Android api_level
  conans/client/build/cmake.py
  conans/test/build_helpers/cmake_test.py
Labels: in review

#2883 Fixed CMake without settings
  conans/client/build/cmake.py
  conans/test/build_helpers/cmake_test.py
  conans/test/integration/cmake_flags_test.py
Labels: in review

#2916 Fixed equals in tuple default_options (#2915)
  conans/model/options.py
  conans/test/integration/options_test.py
Labels: contributor pr

#2909 Make sure tools.which() does not return a dir
  conans/client/tools/files.py
  conans/test/util/tools_test.py
  conans/test/util/which_test.py
  conans/test/utils/context_manager.py
Labels: in review

#2921 fix inconsistent cache with short_paths
  conans/test/functional/short_paths_test.py
  conans/util/windows.py
Labels: in review

#2922 Fix "Package '1' created" message with short_paths=True
  conans/client/installer.py
  conans/client/manager.py
  conans/client/packager.py
  conans/test/functional/create_package_test.py
  conans/test/functional/short_paths_test.py
Labels: in review

#2919 Feature/remove disk search manager
  conans/client/client_cache.py
  conans/client/cmd/export.py
  conans/client/cmd/search.py
  conans/client/cmd/uploader.py
  conans/client/conan_api.py
  conans/client/graph/build_mode.py
  conans/client/graph/graph_builder.py
  conans/client/graph/range_resolver.py
  conans/client/manager.py
  conans/client/remover.py
  conans/client/store/localdb.py
  conans/client/store/sqlite.py
  conans/model/requires.py
  conans/search/search.py
  conans/server/rest/controllers/conan_controller.py
  conans/server/rest/server.py
  conans/server/server_launcher.py
  conans/server/service/service.py
  conans/test/functional/disk_search_test.py
  conans/test/model/version_ranges_test.py
  conans/test/remote/rest_api_test.py
  conans/test/server/service/service_test.py
  conans/test/server/utils/server_launcher.py
  conans/test/utils/tools.py
Labels: in review

#2920 fix export-pkg python reuse
  conans/client/manager.py
  conans/client/tools/env.py
  conans/test/integration/python_build_test.py
Labels: in review

#2932 download refactor
  conans/client/cmd/download.py
  conans/client/installer.py
  conans/client/manager.py
  conans/client/package_installer.py
  conans/client/proxy.py
  conans/client/remote_manager.py
  conans/test/command/download_test.py
  conans/test/integration/manifest_validation_test.py
Labels: in review

#2926 Capturing current remote behavior tests
  conans/client/proxy.py
  conans/test/integration/multi_remotes_test.py
  conans/test/remote_checks_test.py
Labels: in review

#2849 MSBuild runtime when no runtime setting
  conans/client/build/msbuild.py
  conans/test/build_helpers/msbuild_test.py
Labels: in review

#2908 Fixes newlines in vcvars output for vcvars_dict
  conans/client/tools/win.py
  conans/test/util/tools_test.py
Labels: in review

#2885 GCC 8, Clang 7 and std=c++20 support
  conans/client/build/cppstd_flags.py
  conans/client/conf/__init__.py
  conans/client/migrations.py
  conans/test/build_helpers/autotools_configure_test.py
  conans/test/build_helpers/cpp_std_flags_test.py
  conans/test/generators/compiler_args_test.py
Labels: in review

#2937 refactor manifest
  conans/client/client_cache.py
  conans/client/graph/build_requires.py
  conans/client/graph/graph.py
  conans/client/graph/graph_builder.py
  conans/client/graph/printer.py
  conans/client/installer.py
  conans/client/manager.py
  conans/client/manifest_manager.py
  conans/client/printer.py
  conans/client/proxy.py
  conans/client/remote_manager.py
  conans/test/model/transitive_reqs_test.py
  conans/test/model/version_ranges_test.py
Labels: in review

#2803 - automatically set up vcvars for Ninja and NMake generators
  conans/client/build/cmake.py
  conans/test/build_helpers/cmake_test.py
Labels: contributor pr

#1815 - add tools for Apple development
  conans/client/tools/__init__.py
  conans/client/tools/apple.py
  conans/test/util/apple_test.py
Labels: contributor pr, in review

#2869 Feature/fix symlinks
  conans/client/file_copier.py
  conans/test/functional/file_copier_test.py
  conans/test/functional/symlink_package_test.py
  conans/test/integration/symlinks_test.py
Labels: in review

#2927 Fix version class for greater than comparison
  conans/model/version.py
  conans/test/model/version_test.py
Labels: in review

#2939 force truly private
  conans/client/graph/build_mode.py
  conans/client/graph/graph.py
  conans/client/graph/graph_builder.py
  conans/client/installer.py
Labels: in review

#2936 Using Visual Studio macro for userprofile path
  conans/client/generators/visualstudio.py
Labels: contributor pr

#2931 Feature/capture scm
  conans/client/cmd/export.py
  conans/client/generators/virtualenv.py
  conans/client/installer.py
  conans/client/manager.py
  conans/client/source.py
  conans/client/tools/__init__.py
  conans/client/tools/scm.py
  conans/model/scm.py
  conans/paths.py
  conans/test/functional/scm_test.py
  conans/test/util/tools_test.py
  conans/test/utils/tools.py
Labels: in review

#2887 fPIC auto-managed in autotools build helper
  conans/client/build/autotools_environment.py
  conans/test/build_helpers/autotools_configure_test.py
Labels: in review

#2948 Feature/vcvars diff
  conans/client/tools/win.py
  conans/test/util/tools_test.py
Labels: in review

#2949 do not overwrite settings.yml
  conans/client/migrations.py
Labels: in review

#2941 Add vcvars_ver and winsdk_version to tools.vcvars_command
  conans/client/tools/win.py
  conans/test/util/tools_test.py
  conans/test/util/vcvars_arch_test.py
Labels: contributor pr

#2930 Set vcvars in virtualbuildenv generator for visual studio
  conans/client/generators/virtualbuildenv.py
  conans/client/generators/virtualenv.py
  conans/client/tools/win.py
  conans/test/generators/virtualbuildenv_test.py
  conans/test/integration/conan_env_test.py
Labels: in review

#2952 Feature/pkg config improvements
  conans/client/build/autotools_environment.py
  conans/client/build/cmake.py
  conans/client/build/meson.py
  conans/test/build_helpers/autotools_configure_test.py
  conans/test/build_helpers/cmake_test.py
  conans/util/files.py
Labels: in review

#2875 Non-intrusive integration with CMake
  conans/client/build/autotools_environment.py
  conans/client/build/cmake.py
  conans/client/generators/__init__.py
  conans/client/generators/cmake_find_package.py
  conans/client/generators/cmake_paths.py
  conans/test/generators/cmake_find_package_test.py
  conans/test/generators/cmake_paths_test.py
Labels: in review

#2902 Search json output: conan search --json output.json
  .gitignore
  conans/client/cmd/search.py
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/conan_command_output.py
  conans/client/graph/grapher.py
  conans/client/printer.py
  conans/client/recorder/search_recorder.py
  conans/client/recorder/upload_recoder.py
  conans/search/search.py
  conans/test/command/search_test.py
  conans/test/functional/search_recorder_test.py
  conans/test/functional/upload_recorder_test.py
Labels: in review

#2963 fixing symlinked folder bug
  conans/client/file_copier.py
  conans/test/functional/file_copier_test.py
Labels: in review

#2964 fixe get_cased_path
  conans/client/tools/win.py
  conans/test/util/unix_path_test.py
Labels: in review

#2966 scm message changed and added test
  conans/client/cmd/export.py
  conans/test/functional/scm_test.py
Labels: in review

#2967 Fixed and added 20 standard
  conans/client/conf/__init__.py
  conans/client/migrations.py
Labels: in review

#2955 move download
  conans/client/cmd/download.py
  conans/client/conan_api.py
  conans/client/manager.py
Labels: in review

#2969 fixed preprocessor
  conans/client/build/cppstd_flags.py
  conans/test/integration/cppstd_test.py
Labels: in review
