Repository conan-io/conan, pull requests merged in 2018-09, with the labels that each got.

#3453 TestClient: wrap command and output from command in fancy lines
  conans/test/utils/tools.py
Labels: in review

#3454 [fix] Handle winreg.OpenKey exception
  conans/client/tools/win.py
Labels: in review

#3455 [fix] Issues related to OSInfo.bash_path()
  conans/test/util/tools_test.py
Labels: in review

#3468 Feature/add relative config install
  conans/client/conan_api.py
  conans/test/command/config_install_test.py
Labels: contributor pr

#3472 Revert "Merge pull request #3245 from danimtb/feature/3232"
  conans/model/options.py
  conans/test/integration/options_test.py
Labels: in review

#3459 fix should_build for cmake build helper
  conans/client/build/cmake.py
  conans/test/build_helpers/cmake_test.py
Labels: in review

#3464 Removed client-side username checks (#3444)
  conans/client/userio.py
  conans/model/username.py
  conans/test/model/username_test.py
  conans/test/remote/auth_test.py
Labels: contributor pr

#3478 Fix bug detected with downloader output
  conans/__init__.py
  conans/client/rest/rest_client_v1.py
  conans/test/remote/broken_download_test.py
Labels: in review

#3450 Add CONAN_IN_LOCAL_CACHE variable in CMake build_helper
  conans/client/build/cmake.py
  conans/client/build/cmake_flags.py
  conans/client/build/meson.py
  conans/client/generators/cmake_common.py
  conans/test/build_helpers/cmake_test.py
  conans/test/generators/cmake_test.py
Labels: in review

#3490 Use dict.get for get_safe
  conans/model/options.py
Labels: contributor pr

#3479 Add get_repo_root to SCM, use it for path stored in scm_folder.txt (close #3465)
  conans/client/cmd/export.py
  conans/client/tools/scm.py
  conans/model/scm.py
  conans/test/functional/scm_test.py
  conans/test/util/tools_test.py
Labels: in review

#3491 fix *:option pattern for consumers
  conans/client/loader.py
  conans/model/options.py
  conans/test/integration/options_test.py
Labels: in review

#3496 Fixed Git class, wrongly replacing characters from the branch name
  conans/client/tools/scm.py
  conans/test/util/tools_test.py
Labels: in review

#3516 [fix] get_cased_path doesn't raise when path does not exists
  conans/client/tools/win.py
  conans/test/util/unix_path_test.py
Labels: bug, in review

#3521 test for transitive shared flags
  conans/test/integration/cmake_targets_test.py
Labels: in review

#3515 Find libtool when getting building information on Darwin
  conans/client/tools/apple.py
Labels: contributor pr

#3528 reduce propagate complexity from O(n2) to O(n)
  conans/client/installer.py
Labels: in review

#3534 removed dead serialize code
  conans/model/info.py
  conans/test/util/unix_path_test.py
Labels: in review

#3480 upload based on manifest diff, not snapshot
  conans/client/cmd/uploader.py
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/remote_manager.py
  conans/client/rest/auth_manager.py
  conans/client/rest/differ.py
  conans/client/rest/rest_client.py
  conans/client/rest/rest_client_v1.py
  conans/test/command/upload_complete_test.py
  conans/test/command/upload_test.py
  conans/test/remote/rest_api_test.py
Labels: in review

#3442 Client with apiv2 (transfers in one step)
  .ci/jenkins/Jenkinsfile
  .ci/jenkins/runner.py
  conans/client/rest/rest_client.py
  conans/client/rest/rest_client_common.py
  conans/client/rest/rest_client_v1.py
  conans/client/rest/rest_client_v2.py
  conans/server/conf/default_server_conf.py
  conans/server/rest/controllers/v1/conan_controller.py
  conans/server/rest/controllers/v2/conan_controller.py
  conans/server/service/service.py
  conans/server/service/service_v2.py
  conans/server/store/disk_adapter.py
  conans/server/store/server_store.py
  conans/test/functional/conan_trace_file_test.py
  conans/test/remote/auth_bearer_test.py
  conans/test/remote/broken_download_test.py
  conans/test/server/service/service_test.py
Labels: in review

#3525 fixing transitive private bug
  conans/client/graph/graph_builder.py
  conans/test/integration/private_deps_test.py
Labels: in review

#3537 changing processing of exports exclude patterns
  conans/client/file_copier.py
  conans/test/integration/symlinks_test.py
Labels: in review

#3445 Implement add_repository for SystemPackageTool (only AptTool) (close #3385)
  conans/client/tools/system_pm.py
  conans/test/util/tools_test.py
Labels: in review

#3443 add processing indicator during files compression
  conans/client/remote_manager.py
Labels: contributor pr

#3562 Don't retry when NotFoundException
  conans/client/rest/uploader_downloader.py
  conans/test/functional/download_retries_test.py
Labels: in review

#3560 conanfile reserved attrs and methods
  conans/client/graph/graph.py
  conans/client/graph/graph_builder.py
  conans/client/graph/graph_manager.py
  conans/client/installer.py
  conans/client/loader.py
  conans/client/tools/win.py
  conans/model/conan_file.py
  conans/test/model/conanfile_test.py
  conans/test/util/tools_test.py
Labels: in review

#3561 configuration print for install
  conans/client/manager.py
  conans/test/command/create_test.py
  conans/test/command/install_test.py
Labels: in review

#3579 - use forward slashes for short paths
  conans/util/windows.py
Labels: contributor pr

#3033 Fix check for installed apt packages (#3032)
  conans/client/tools/system_pm.py
  conans/test/util/tools_test.py
Labels: in review

#3410 Add more meaninful error when parsing conanfile reference (closes #3204)
  conans/model/ref.py
  conans/test/command/new_test.py
  conans/test/model/ref_test.py
  conans/util/config_parser.py
Labels: in review

#3581 - fix PowerPC architecture detection
  conans/client/tools/oss.py
  conans/test/util/detected_architecture_test.py
Labels: contributor pr

#3576 Feature/reuse python scm
  conans/client/cmd/export.py
  conans/model/scm.py
  conans/test/functional/scm_test.py
  conans/test/integration/python_build_test.py
Labels: in review

#3586 if/else to test. It was failing with cmake >=3.12
  conans/client/build/cmake.py
  conans/test/integration/cmake_flags_test.py
Labels: engineering, in review

#3600 fix get short_paths
  conans/client/local_file_getter.py
  conans/test/functional/short_paths_test.py
Labels: in review

#3388 Added --libdir parameter to autotools configure
  conans/client/build/autotools_environment.py
  conans/test/build_helpers/autotools_configure_test.py
Labels: in review

#3517 Add ConanInvalidConfiguration exception and handle error codes.
  conans/client/command.py
  conans/errors.py
  conans/test/command/invalid_configuration_test.py
Labels: enhancement, in review

#3555 Conan plugins
  conans/client/client_cache.py
  conans/client/cmd/download.py
  conans/client/cmd/export.py
  conans/client/cmd/uploader.py
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/conf/__init__.py
  conans/client/installer.py
  conans/client/manager.py
  conans/client/packager.py
  conans/client/plugin_manager.py
  conans/client/remote_manager.py
  conans/client/source.py
  conans/test/command/info_test.py
  conans/test/functional/create_package_test.py
  conans/test/functional/plugin_manager_test.py
  conans/test/integration/plugin_test.py
  conans/test/utils/tools.py
Labels: in review, plugin

#3603 Not muted exception and added new archs for triplet detection
  conans/client/build/autotools_environment.py
  conans/client/tools/oss.py
  conans/test/build_helpers/autotools_configure_test.py
  conans/test/util/tools_test.py
Labels: in review

#3503 Use self.cpp_info.libdirs as folders for tools.collect_libs()
  conans/client/tools/files.py
  conans/test/util/tools_test.py
Labels: in review

#3601 fix bug: bad replacement if scm attribute was the last one in ClassDef
  conans/client/cmd/export.py
  conans/test/client/__init__.py
  conans/test/client/cmd/__init__.py
  conans/test/client/cmd/export_test.py
Labels: in review

#3628 fixing multiple python requires collission
  conans/client/graph/python_requires.py
  conans/test/integration/python_build_test.py
Labels: in review

#3623 Validate ConanFileReference only if requested
  conans/model/ref.py
Labels: engineering, in review

#3574 - allow vcvars for clang-cl
  conans/client/conf/detect.py
  conans/client/tools/win.py
  conans/test/util/vcvars_clangcl_test.py
Labels: in review

#3598 Clean repeated entries in PATH after vcvars call
  conans/client/tools/win.py
  conans/test/util/tools_test.py
Labels: in review

#3486 Add cmake flag 'CMAKE_OSX_DEPLOYMENT_TARGET' according to settings.os.version
  conans/client/build/cmake_flags.py
  conans/test/build_helpers/cmake_test.py
Labels: in review
