Repository conan-io/conan, pull requests merged in 2019-01, with the labels that each got.

#4207 Remove credentials from 'url' for SCM replacement
  conans/client/cmd/export.py
  conans/client/tools/scm.py
  conans/model/scm.py
  conans/test/functional/scm/__init__.py
  conans/test/functional/scm/test_url_auto.py
  conans/test/unittests/client/tools/scm/__init__.py
  conans/test/unittests/client/tools/scm/test_git.py
  conans/test/unittests/client/tools/scm/test_scm_base.py
  conans/test/unittests/client/tools/scm/test_svn.py
Labels: stage: review

#4175 CI Fixes: rest api failures
  .ci/jenkins/Jenkinsfile
Labels: stage: review

#4205 Remove version_checker from client
  conans/client/conan_api.py
  conans/client/conf/__init__.py
  conans/client/rest/rest_client.py
  conans/client/rest/version_checker.py
  conans/server/rest/api_v1.py
  conans/server/rest/api_v2.py
  conans/server/rest/bottle_plugins/authorization_header.py
  conans/server/rest/bottle_plugins/http_basic_authentication.py
  conans/server/rest/bottle_plugins/jwt_authentication.py
  conans/server/rest/bottle_plugins/return_handler.py
  conans/server/rest/bottle_plugins/version_checker.py
  conans/server/rest/controllers/ping_controller.py
  conans/server/rest/server.py
  conans/test/functional/remote/rest_api_test.py
  conans/test/integration/version_check_test.py
  conans/test/utils/server_launcher.py
  conans/test/utils/tools.py
Labels: stage: review

#4217 reorg of build_requires tests
  conans/client/manager.py
  conans/test/functional/build_requires/__init__.py
  conans/test/functional/build_requires/build_requires_test.py
  conans/test/functional/build_requires/profile_build_requires_test.py
  conans/test/functional/build_requires/profile_build_requires_testing_test.py
  conans/test/functional/build_requires/profile_requires_test.py
  conans/test/functional/command/create_test.py
  conans/test/unittests/client/conanfile_loader_test.py
  conans/test/unittests/client/profile_loader_test.py
  conans/test/unittests/client/userio_test.py
  conans/test/unittests/model/transitive_reqs_test.py
Labels: stage: review

#3945 Expose Conan arch & build_type settings, and add conan_basic_setup()
  conans/client/generators/premake.py
  conans/test/functional/generators/premake_test.py
  conans/test/unittests/client/generators/premake_test.py
Labels: complex: low, component: Build, priority: low, stage: review

#4227 Fix add_cmake_flag in cmake helper
  conans/client/build/cmake_flags.py
Labels: complex: low, contributor pr, priority: high, stage: review, type: bug

#4229 Fix migrations
  conans/conan_server.py
  conans/server/launcher.py
  conans/server/migrate.py
  conans/server/migrations.py
  conans/server/server_launcher.py
  conans/server/store/server_store.py
Labels: stage: review

#4241 refactor cmake flags
  conans/client/build/cmake_flags.py
  conans/client/build/compiler_flags.py
  conans/test/functional/build_helpers/cmake_flags_test.py
Labels: stage: review

#4247 optimizing slow tests
  conans/test/functional/command/create_test.py
  conans/test/integration/complete_test.py
  conans/test/integration/conan_test_test.py
Labels: stage: review

#4228 reorg of python requires tests
  conans/test/functional/python_requires/__init__.py
  conans/test/functional/python_requires/python_package_reuse_test.py
  conans/test/functional/python_requires/python_requires_test.py
  conans/test/functional/scm/scm_test.py
Labels: stage: review

#4231 reorg and optimize tests
  conans/test/functional/command/upload_compression_test.py
  conans/test/functional/graph/version_range_error_test.py
  conans/test/functional/graph/version_ranges_diamond_test.py
  conans/test/integration/syncronize_test.py
Labels: stage: review

#4255 Added missing build helpers unit tests
  .gitignore
  conans/test/unittests/client/build/__init__.py
  conans/test/unittests/client/build/autotools_environment_test.py
  conans/test/unittests/client/build/cmake_test.py
  conans/test/unittests/client/build/compiler_flags_test.py
  conans/test/unittests/client/build/cpp_std_flags_test.py
  conans/test/unittests/client/build/meson_test.py
  conans/test/unittests/client/build/msbuild_test.py
  conans/test/unittests/client/build/visual_environment.py
Labels: complex: low, priority: high, stage: review

#4224 feature/enabling environment variables unset action
  conans/client/tools/env.py
  conans/test/unittests/client/tools/test_env.py
Labels: contributor pr, stage: review

#4256 Fixed bug with cached default profile
  conans/client/client_cache.py
  conans/test/functional/conan_api/two_conan_creates_test.py
Labels: stage: review

#4181 Feature: link editable packages
  conans/client/client_cache.py
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/conan_command_output.py
  conans/client/graph/graph.py
  conans/client/graph/graph_binaries.py
  conans/client/graph/proxy.py
  conans/client/installer.py
  conans/client/manager.py
  conans/client/manifest_manager.py
  conans/client/printer.py
  conans/client/remover.py
  conans/model/editable_cpp_info.py
  conans/paths.py
  conans/paths/__init__.py
  conans/paths/package_layouts/__init__.py
  conans/paths/package_layouts/package_cache_layout.py
  conans/paths/package_layouts/package_editable_layout.py
  conans/paths/simple_paths.py
  conans/server/store/disk_adapter.py
  conans/server/store/server_store.py
  conans/test/functional/editable/__init__.py
  conans/test/functional/editable/commands/__init__.py
  conans/test/functional/editable/commands/info_on_child_test.py
  conans/test/functional/editable/commands/info_test.py
  conans/test/functional/editable/commands/inspect_test.py
  conans/test/functional/editable/consume_header_only_test.py
  conans/test/functional/editable/consume_settings_and_options_test.py
  conans/test/functional/editable/forbidden_commands_test.py
  conans/test/functional/editable/graph_related_test.py
  conans/test/functional/editable/link_create_test.py
  conans/test/functional/editable/link_remove_test.py
  conans/test/functional/old/package_copier_test.py
  conans/test/functional/old/paths_test.py
  conans/test/integration/manifest_validation_test.py
  conans/test/unittests/model/editable_cpp_info/__init__.py
  conans/test/unittests/model/editable_cpp_info/apply_test.py
  conans/test/unittests/model/editable_cpp_info/parse_test.py
  conans/test/unittests/model/editable_cpp_info/work_on_items_test.py
  conans/test/unittests/model/version_ranges_test.py
  conans/test/utils/server_launcher.py
  conans/test/utils/tools.py
Labels: stage: review

#4273 fixing version ranges with spaces
  conans/model/ref.py
  conans/test/functional/old/paths_test.py
  conans/test/unittests/model/ref_test.py
  conans/test/unittests/model/version_ranges_test.py
Labels: stage: review

#4280 remove 'revisions_enabled' from conf
  conans/client/conf/__init__.py
  conans/client/rest/rest_client_v2.py
  conans/server/service/service_v2.py
  conans/test/utils/tools.py
Labels: stage: review

#4279 Import configparser from six for Python2 compatiblity
  conans/model/editable_cpp_info.py
Labels: stage: review

#4283 remove old custom env context
  conans/test/integration/go_complete_test.py
  conans/test/integration/go_diamond_test.py
  conans/test/utils/context_manager.py
Labels: stage: review

#4211 Feature/b2 rooted dep projects
  conans/client/generators/b2.py
  conans/test/unittests/client/generators/b2_test.py
Labels: stage: review

#4275 move loading of manifests to layout
  conans/client/cache.py
  conans/client/cmd/export.py
  conans/client/cmd/export_pkg.py
  conans/client/cmd/search.py
  conans/client/cmd/uploader.py
  conans/client/conan_command_output.py
  conans/client/graph/graph_binaries.py
  conans/client/graph/proxy.py
  conans/client/installer.py
  conans/client/remote_manager.py
  conans/client/remover.py
  conans/paths/package_layouts/package_cache_layout.py
  conans/paths/package_layouts/package_editable_layout.py
  conans/search/search.py
  conans/test/functional/command/upload_complete_test.py
  conans/test/functional/command/upload_test.py
  conans/test/functional/old/package_integrity_test.py
  conans/test/utils/tools.py
Labels: stage: review

#4292 Use old interface of ConfigParser
  conans/model/editable_cpp_info.py
  conans/test/unittests/model/editable_cpp_info/apply_test.py
  conans/test/unittests/model/editable_cpp_info/parse_test.py
Labels: stage: review

#4259 Feature/cleaner config install
  conans/client/conf/config_installer.py
Labels: contributor pr, stage: review

#4299 Feature: define environment variables for CTest
  conans/client/build/cmake.py
  conans/test/unittests/client/build/cmake_test.py
Labels: stage: review

#4303 Added sha1 header always
  conans/client/rest/uploader_downloader.py
Labels: stage: review

#4320 Fix develop testsuite: MSBuild verbosity level
  conans/test/functional/build_helpers/msbuild_test.py
Labels: stage: review

#4276 disable cmake compiler check language=None
  conans/client/generators/cmake_common.py
  conans/test/functional/generators/cmake_test.py
  conans/test/functional/old/libcxx_setting_test.py
Labels: stage: review

#4239 Feature: add definitions to MSBuild (and build_sln_command)
  conans/client/build/msbuild.py
  conans/client/tools/win.py
  conans/test/unittests/client/build/msbuild_test.py
Labels: stage: review

#4313 Fix: ensure is_windows, detect_windows_subsystem, uname work under MSYS/Cygwin
  conans/client/conf/detect.py
  conans/client/tools/oss.py
  conans/test/unittests/client/conf/detect/__init__.py
  conans/test/unittests/client/conf/detect/detected_os_test.py
  conans/test/unittests/client/tools/os_info/__init__.py
  conans/test/unittests/client/tools/os_info/osinfo_test.py
Labels: stage: review

#4317 fixed uncontrolled error when server responds 200
  conans/client/rest/rest_client_common.py
  conans/server/rest/multipart_encoder.py
  conans/server/rest/server.py
  conans/server/service/mime.py
  conans/test/functional/command/remote_verify_ssl_test.py
  conans/test/functional/old/download_retries_test.py
  conans/test/functional/remote/server_error_test.py
Labels: stage: review

#4298 Feature: add CONAN_CMAKE_PROGRAM
  conans/client/build/cmake.py
  conans/client/conf/__init__.py
  conans/test/unittests/client/build/cmake_test.py
Labels: stage: review

#4301 Consider scm_folder.txt only for developing packages
  conans/client/graph/build_mode.py
  conans/client/source.py
  conans/test/functional/scm/test_local_modified.py
Labels: stage: review

#4324 Fix: ensure tools.environment_append doesn't raise trying to unset variables
  conans/client/tools/env.py
  conans/test/unittests/client/tools/test_env.py
Labels: stage: review

#4326 Fixed mocked check_output() for uname command
  conans/test/unittests/client/tools/os_info/osinfo_test.py
Labels: stage: review

#4306 Add git.get_tag() and svn.get_tag()
  conans/client/tools/scm.py
  conans/test/unittests/util/tools_test.py
Labels: stage: review

#4327 Feature/msbuild verbosity priority
  conans/client/build/cmake.py
  conans/client/build/msbuild.py
  conans/test/unittests/client/tools/os_info/osinfo_test.py
Labels: stage: review

#4305 #3799 Accept full reference for --build
  conans/client/graph/build_mode.py
  conans/client/graph/graph_binaries.py
  conans/test/functional/command/build_test.py
  conans/test/unittests/client/graph/build_mode_test.py
Labels: stage: review

#4325 Fix bug in server revisions
  conans/server/revision_list.py
  conans/server/store/server_store.py
Labels: stage: review

#4332 FIX DEVELOP: cmake generator default choice
  conans/test/functional/generators/cmake_generator_test.py
  conans/test/unittests/client/build/cmake_flags.py
Labels: priority: critical, stage: review

#4329 Fix pydoc of package_id
  conans/model/conan_file.py
Labels: stage: review

#4296 Fix: Update premake generator, rename conanbuildinfo.premake -> conanbuildinfo.premake.lua, conan_cppdefines -> conan_defines
  conans/client/generators/premake.py
  conans/paths.py
  conans/paths/__init__.py
  conans/test/functional/generators/premake_test.py
  conans/test/unittests/client/generators/premake_test.py
Labels: stage: review

#3868 [SVN] Add several tests with different locking mechanism
  conans/client/cmd/export.py
  conans/test/functional/scm/scm_test.py
  conans/test/unittests/util/files/__init__.py
  conans/test/unittests/util/files/test_remove.py
  conans/util/files.py
Labels: stage: review

#4308 Composable profiles
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/profile_loader.py
  conans/test/functional/configuration/profile_test.py
Labels: stage: review

#4341 #4339 Remove profile from cmake gen tests
  conans/test/functional/generators/cmake_generator_test.py
  conans/test/unittests/client/build/cmake_flags.py
Labels: stage: review

#4361 fix FileNotFoundError is py3 only
  conans/client/tools/scm.py
  conans/server/store/server_store.py
  conans/test/unittests/util/tools_test.py
Labels: stage: review

#4358 generator template
  conans/client/generators/__init__.py
  conans/client/loader.py
  conans/test/functional/generators/custom_generator_test.py
Labels: stage: review

#4362 fix caching api
  conans/client/conan_api.py
  conans/client/graph/python_requires.py
  conans/client/loader.py
  conans/test/functional/conan_api/two_conan_creates_test.py
Labels: stage: review

#4197 Feature/install ref
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/graph/graph_manager.py
  conans/client/loader.py
  conans/model/graph_info.py
  conans/test/functional/command/install_test.py
Labels: stage: review

#4354 #3812 Remove system requirements from cache
  conans/client/cache.py
  conans/client/command.py
  conans/conan.py
  conans/test/integration/system_reqs_test.py
Labels: stage: review

#4378 moved files to new cache package
  conans/client/cache/__init__.py
  conans/client/cache/cache.py
  conans/client/cache/editable.py
  conans/client/cache/remote_registry.py
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/conf/__init__.py
  conans/client/conf/config_installer.py
  conans/client/manager.py
  conans/client/manifest_manager.py
  conans/client/migrations.py
  conans/client/remote_manager.py
  conans/client/remover.py
  conans/test/functional/command/config_install_test.py
  conans/test/functional/configuration/default_profile_test.py
  conans/test/functional/configuration/registry_test.py
  conans/test/integration/conf_default_settings_test.py
  conans/test/unittests/search/disk_search_test.py
  conans/test/unittests/util/client_conf_test.py
  conans/test/unittests/util/tools_test.py
  conans/test/utils/tools.py
Labels: stage: review

#4375 Fix output stream failures (Windows)
  conans/client/output.py
  conans/test/unittests/client/conan_output_test.py
  conans/util/progress_bar.py
Labels: stage: review

#4380 Remove double application of env vars from profile
  conans/client/loader.py
  conans/test/functional/configuration/profile_test.py
  conans/test/unittests/client/generators/virtualenv_test.py
  conans/test/unittests/client/loader_test.py
Labels: stage: review, type: bug

#4391 Fix: Meson in case of package_folder == None
  conans/client/build/meson.py
  conans/test/unittests/client/build/meson_test.py
Labels: stage: review

#4390 Fix: get_cross_building_settings for MSYS
  conans/client/build/autotools_environment.py
  conans/client/conf/detect.py
  conans/client/tools/oss.py
  conans/test/functional/command/install_test.py
  conans/test/unittests/client/conf/detect/detected_os_test.py
  conans/test/unittests/client/tools/oss/__init__.py
  conans/test/unittests/client/tools/oss/get_cross_building_settings_test.py
Labels: stage: review

#4359 Add json output to info command (both console and file)
  conans/client/command.py
  conans/client/conan_command_output.py
  conans/client/printer.py
  conans/test/functional/command/info_command_test.py
  conans/test/functional/command/info_test.py
  conans/util/locks.py
Labels: stage: review

#4249 Fix: handle corner cases related to SCM with local sources optimization
  conans/client/cmd/export.py
  conans/client/source.py
  conans/client/tools/scm.py
  conans/model/scm.py
  conans/test/functional/command/source_test.py
  conans/test/functional/scm/scm_test.py
  conans/test/functional/scm/test_command_export.py
  conans/test/functional/scm/workflows/__init__.py
  conans/test/functional/scm/workflows/common.py
  conans/test/functional/scm/workflows/test_conanfile_in_repo_root.py
  conans/test/functional/scm/workflows/test_conanfile_in_subfolder.py
  conans/test/functional/scm/workflows/test_scm_subfolder.py
  conans/test/unittests/client/cmd/export/__init__.py
  conans/test/unittests/client/cmd/export/test_capture_export_scm_data.py
  conans/test/unittests/client/source/__init__.py
  conans/test/unittests/client/source/test_run_scm.py
Labels: stage: review

#4405 Fix develop: add quotes to word so it is a string
  conans/test/functional/scm/scm_test.py
Labels: stage: review

#4416 [typo] Remove unused code
  conans/test/functional/command/info_command_test.py
Labels: stage: review

#4429 Feature/fix casing test win
  conans/client/tools/win.py
  conans/test/unittests/client/cmd/export/test_capture_export_scm_data.py
  conans/test/unittests/client/source/test_run_scm.py
  conans/test/utils/test_files.py
Labels: stage: review
