Repository conan-io/conan, pull requests merged in 2019-02, with the labels that each got.

#4435 remove build mode check
  conans/client/graph/graph_manager.py
Labels: stage: review

#4446 Post export function of hooks is called before computing the digest
  conans/client/cmd/export.py
  conans/test/functional/hooks/__init__.py
  conans/test/functional/hooks/test_post_export.py
  conans/util/files.py
Labels: stage: review

#4426 Use named arguments when calling to hook functions
  conans/client/hook_manager.py
Labels: stage: review

#4455 fix patch strip
  conans/client/tools/files.py
  conans/test/unittests/tools/__init__.py
  conans/test/unittests/tools/files_patch_test.py
  conans/test/unittests/util/conanfile_tools_test.py
Labels: stage: review

#4408 Show remote name for upload command output
  conans/client/cmd/uploader.py
  conans/test/functional/command/upload_complete_test.py
  conans/test/functional/command/upload_test.py
Labels: stage: review

#4448 fixing editable package revisions
  conans/client/graph/graph_builder.py
  conans/test/functional/editable/transitive_editable_test.py
Labels: stage: review

#4458 fixing regression of graph_info not having root
  conans/model/graph_info.py
  conans/test/functional/command/info_test.py
Labels: stage: review

#4293 Feature/revisions list endpoints
  conans/client/cmd/uploader.py
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/conan_command_output.py
  conans/client/installer.py
  conans/client/remote_manager.py
  conans/client/rest/auth_manager.py
  conans/client/rest/client_routes.py
  conans/client/rest/rest_client.py
  conans/client/rest/rest_client_common.py
  conans/client/rest/rest_client_v1.py
  conans/client/rest/rest_client_v2.py
  conans/model/package_metadata.py
  conans/paths/package_layouts/package_cache_layout.py
  conans/server/rest/api_v2.py
  conans/server/rest/controllers/v2/revisions_controller.py
  conans/server/revision_list.py
  conans/server/service/service.py
  conans/server/service/service_v2.py
  conans/server/store/server_store.py
  conans/test/functional/command/remove_test.py
  conans/test/functional/command/search_test.py
  conans/test/functional/command/upload_complete_test.py
  conans/test/functional/old/conan_trace_file_test.py
  conans/test/functional/old/package_integrity_test.py
  conans/test/integration/multi_remote_test.py
  conans/test/integration/revisions_test.py
  conans/test/integration/syncronize_test.py
  conans/test/unittests/client/cache_test.py
  conans/test/unittests/client/util/time_test.py
  conans/test/unittests/server/revision_list_test.py
  conans/test/utils/tools.py
  conans/util/dates.py
Labels: stage: review

#4464 Fix warning message for package folder (#4438)
  conans/client/file_copier.py
  conans/client/packager.py
  conans/test/functional/command/create_test.py
  conans/test/functional/command/export_pkg_test.py
  conans/test/functional/command/package_test.py
  conans/test/functional/conanfile/imports_tests.py
  conans/test/functional/old/conan_trace_file_test.py
  conans/test/integration/complete_test.py
Labels: stage: review

#4488 fixed abs-path in conanbuild.props
  conans/client/build/msbuild.py
  conans/test/unittests/client/build/msbuild_test.py
Labels: priority: critical, stage: review

#4476 renaming conan->recipe
  conans/client/cmd/export_pkg.py
  conans/client/cmd/search.py
  conans/client/cmd/uploader.py
  conans/client/conan_command_output.py
  conans/client/graph/graph_binaries.py
  conans/client/graph/proxy.py
  conans/client/installer.py
  conans/client/remote_manager.py
  conans/client/remover.py
  conans/client/rest/auth_manager.py
  conans/client/rest/rest_client.py
  conans/client/rest/rest_client_common.py
  conans/client/rest/rest_client_v1.py
  conans/client/rest/rest_client_v2.py
  conans/paths/package_layouts/package_cache_layout.py
  conans/server/rest/controllers/v1/conan_controller.py
  conans/test/functional/command/upload_complete_test.py
  conans/test/functional/command/upload_test.py
  conans/test/functional/remote/auth_bearer_test.py
  conans/test/functional/remote/rest_api_test.py
Labels: stage: review

#4495 Do not allow an alias to override an existing package
  conans/client/conan_api.py
  conans/test/functional/command/alias_test.py
Labels: stage: review

#4489 fix meson build_type
  conans/client/build/meson.py
  conans/test/unittests/client/build/meson_test.py
Labels: contributor pr

#4503 Revert "fix meson build_type"
  conans/client/build/meson.py
  conans/test/unittests/client/build/meson_test.py
Labels: stage: review

#4504 fix meson build_type (#4489)
  conans/client/build/meson.py
  conans/test/unittests/client/build/meson_test.py
Labels: stage: review

#4510 profile defined build requires do not recurse
  conans/client/graph/graph_manager.py
  conans/test/functional/build_requires/profile_build_requires_test.py
Labels: stage: review

#4509 Revert CMake default generator on Windows
  conans/client/build/cmake.py
  conans/client/build/cmake_flags.py
  conans/test/functional/build_helpers/cmake_flags_test.py
  conans/test/functional/generators/cmake_generator_test.py
  conans/test/unittests/client/build/cmake_test.py
Labels: stage: review, type: bug

#4539 fix for using @ in conanfile.txt imports
  conans/client/loader_txt.py
  conans/test/functional/conanfile/imports_tests.py
Labels: stage: review

#4502 bugfix: Wrong param in function `search_packages`
  conans/client/cmd/search.py
  conans/test/functional/command/search_test.py
Labels: stage: review

#4547 Fixes future possible downgrade from 1.13 to 1.12.2
  conans/model/package_metadata.py
Labels: stage: review

#4518 remove output warning in MSBuild
  conans/client/build/msbuild.py
  conans/client/generators/virtualbuildenv.py
  conans/test/functional/build_helpers/msbuild_test.py
Labels: stage: review

#4494 [CLI] Accept a PackageReference in the command 'get' (preferred)
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/file_copier.py
  conans/client/local_file_getter.py
  conans/errors.py
  conans/model/ref.py
  conans/paths/package_layouts/package_cache_layout.py
  conans/paths/package_layouts/package_editable_layout.py
  conans/test/functional/command/conan_get_test.py
  conans/test/unittests/client/file_copier/__init__.py
  conans/test/unittests/client/file_copier/test_report_copied_files.py
  conans/test/utils/conanfile.py
Labels: stage: review

#4541 Fix: ensure tools.OSInfo doesn't raise in MSYS/Cygwin environment
  conans/client/tools/oss.py
  conans/test/unittests/client/conf/detect/detected_os_test.py
  conans/test/unittests/client/tools/os_info/osinfo_test.py
Labels: stage: review

#4552 Add lock to rest_api tests
  .ci/jenkins/Jenkinsfile
Labels: stage: review

#4526 Fix Anonymous user behavior + Artifactory test framework
  conans/client/rest/rest_client_v2.py
  conans/client/rest/uploader_downloader.py
  conans/test/integration/revisions_test.py
  conans/test/utils/tools.py
Labels: stage: review

#4511 Feature/binary analyzer changes
  conans/client/cmd/export_pkg.py
  conans/client/conan_command_output.py
  conans/client/graph/graph.py
  conans/client/graph/graph_binaries.py
  conans/client/graph/graph_builder.py
  conans/client/graph/graph_manager.py
  conans/client/graph/grapher.py
  conans/client/graph/printer.py
  conans/client/installer.py
  conans/client/manifest_manager.py
  conans/model/info.py
  conans/test/unittests/client/graph/version_ranges_graph_test.py
  conans/test/unittests/model/fake_retriever.py
  conans/test/unittests/model/transitive_reqs_test.py
  conans/test/unittests/model/version_ranges_test.py
Labels: stage: review

#4560 fix develop
  conans/errors.py
  conans/server/service/v1/service.py
  conans/test/functional/command/conan_get_test.py
Labels: stage: review

#4533 Feature/upload revisions
  conans/client/cmd/copy.py
  conans/client/cmd/uploader.py
  conans/client/command.py
  conans/client/remote_manager.py
  conans/client/rest/auth_manager.py
  conans/client/rest/rest_client.py
  conans/client/rest/rest_client_common.py
  conans/test/functional/command/copy_packages_test.py
  conans/test/functional/command/upload_complete_test.py
  conans/test/functional/command/upload_test.py
  conans/test/functional/remote/rest_api_test.py
  conans/test/integration/revisions_test.py
  conans/test/unittests/client/remote_manager_test.py
  conans/test/unittests/client/util/files_test.py
Labels: stage: review

#4556 Close the sqlite3 database after each usage
  conans/client/cmd/user.py
  conans/client/conan_api.py
  conans/client/store/localdb.py
  conans/test/unittests/util/local_db_test.py
Labels: stage: review

#4575 Parsing from Artifactory ISO8601
  conans/test/integration/revisions_test.py
  conans/test/unittests/client/util/time_test.py
  conans/util/dates.py
Labels: stage: review

#4594 Return empty list if env variable is empty
  conans/test/unittests/util/env_reader.py
  conans/util/env_reader.py
Labels: stage: review

#4568 Remove package references associated to a remote in *registry.json* when that remote is deleted
  conans/client/cache/remote_registry.py
  conans/test/functional/command/upload_test.py
Labels: stage: review

#4571 check SettingsItem return type
  conans/model/settings.py
  conans/test/unittests/model/settings_test.py
Labels: stage: review

#4608 Fix: pass argument 'global_output' to tool
  conans/tools.py
Labels: stage: review

#4347 Feature: detect_windows_subsystem recognizes WSL
  conans/client/tools/oss.py
  conans/test/unittests/client/tools/os_info/osinfo_test.py
Labels: stage: review

#4481 Rebase Workspaces on Editable packages
  conans/client/build/cmake.py
  conans/client/cache/editable.py
  conans/client/cmd/export_pkg.py
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/graph/graph.py
  conans/client/graph/graph_binaries.py
  conans/client/graph/graph_builder.py
  conans/client/graph/graph_manager.py
  conans/client/graph/printer.py
  conans/client/installer.py
  conans/client/manager.py
  conans/model/editable_cpp_info.py
  conans/model/workspace.py
  conans/paths/package_layouts/package_cache_layout.py
  conans/paths/package_layouts/package_editable_layout.py
  conans/search/search.py
  conans/test/functional/editable/commands/info_on_child_test.py
  conans/test/functional/editable/commands/info_test.py
  conans/test/functional/editable/commands/inspect_test.py
  conans/test/functional/editable/consume_header_only_test.py
  conans/test/functional/editable/consume_settings_and_options_test.py
  conans/test/functional/editable/forbidden_commands_test.py
  conans/test/functional/editable/graph_related_test.py
  conans/test/functional/editable/layouts_test.py
  conans/test/functional/editable/link_create_test.py
  conans/test/functional/editable/link_remove_test.py
  conans/test/functional/editable/transitive_editable_test.py
  conans/test/integration/workspace_test.py
  conans/test/unittests/model/editable_cpp_info/apply_test.py
  conans/test/unittests/model/editable_cpp_info/parse_test.py
  conans/test/unittests/model/editable_cpp_info/work_on_items_test.py
  conans/test/unittests/model/transitive_reqs_test.py
Labels: stage: review

#4595 Raise if using 'conan search ... --revisions' with the feature disabled
  conans/client/command.py
  conans/test/functional/command/search_test.py
Labels: stage: review

#4583 fixing virtualbuildenv
  conans/client/generators/virtualbuildenv.py
  conans/client/generators/virtualenv.py
  conans/test/functional/generators/cmake_generator_test.py
  conans/test/integration/build_environment_test.py
  conans/test/unittests/client/build/cmake_flags.py
  conans/test/unittests/client/build/visual_environment.py
Labels: stage: review

#4580 Fix SCM replacement with comments below it
  conans/client/cmd/export.py
  conans/test/unittests/client/cmd/ast_replacement_scm_test.py
Labels: stage: review

#4611 Deprecate 'cppflags' in favor of 'cxxflags' in class CppInfo
  conans/model/build_info.py
Labels: stage: review

#4591 Command 'conan profile list' will now list profiles recursively
  conans/client/cmd/profile.py
  conans/test/functional/command/profile_test.py
Labels: contributor pr, stage: review, type: ux

#4618 HotFix: FileNotFoundError is not py2
  conans/client/tools/oss.py
Labels: stage: review, type: bug

#4627 Exclude pylint==2.3.0 (html-escaped chars in json output)
  conans/requirements.txt
Labels: complex: low, priority: critical, stage: review, type: bug, type: ux

#4625 refactor after workspaces
  conans/client/conan_api.py
  conans/client/installer.py
  conans/model/editable_layout.py
  conans/model/workspace.py
  conans/paths/package_layouts/package_editable_layout.py
  conans/test/functional/editable/consume_header_only_test.py
  conans/test/functional/editable/consume_settings_and_options_test.py
  conans/test/functional/editable/editable_add_test.py
  conans/test/functional/editable/editable_remove_test.py
  conans/test/functional/editable/layouts_test.py
  conans/test/functional/workspace/__init__.py
  conans/test/functional/workspace/workspace_test.py
  conans/test/unittests/model/editable_layout/__init__.py
  conans/test/unittests/model/editable_layout/apply_test.py
  conans/test/unittests/model/editable_layout/load_data_test.py
  conans/test/unittests/model/editable_layout/parse_test.py
Labels: stage: review

#4264 Avoid warning message from SVN check function
  conans/client/cmd/export.py
  conans/client/tools/scm.py
  conans/model/scm.py
  conans/test/functional/scm/test_command_export.py
  conans/test/unittests/model/scm_test.py
  conans/test/unittests/util/tools_test.py
Labels: complex: low, component: scm, priority: low, stage: review, type: ux

#4626 [Fix] Search command: catch exception when no reference is passed
  conans/client/command.py
  conans/test/functional/command/search_test.py
Labels: stage: review
