Repository conan-io/conan, pull requests merged in 2019-03, with the labels that each got.

#4496 Remove cache object from code related to 'export' commands
  conans/client/cache/cache.py
  conans/client/cmd/export.py
  conans/client/cmd/search.py
  conans/client/cmd/uploader.py
  conans/client/conan_api.py
  conans/client/graph/proxy.py
  conans/client/migrations.py
  conans/client/remover.py
  conans/paths/package_layouts/package_cache_layout.py
  conans/paths/package_layouts/package_editable_layout.py
  conans/paths/simple_paths.py
  conans/search/search.py
  conans/test/functional/old/path_limit_test.py
  conans/test/unittests/client/cmd/export/test_capture_export_scm_data.py
  conans/test/unittests/search/disk_search_test.py
Labels: stage: review

#4615 fixing not created packages with short_paths - upload
  conans/client/cmd/uploader.py
  conans/client/remover.py
  conans/test/functional/command/info_folders_test.py
  conans/test/functional/command/upload_test.py
  conans/test/functional/old/package_integrity_test.py
Labels: stage: review

#4670 [FIX CI] Fix upload test with PREF being discarded even when not existing
  conans/client/cmd/uploader.py
Labels: stage: review

#4661 Adding armv5 archs to the settings.yml file
  conans/client/conf/__init__.py
Labels: stage: review

#4663 Fail nicely without revisions and only_v2
  conans/__init__.py
  conans/client/conan_api.py
  conans/client/rest/rest_client.py
  conans/errors.py
  conans/test/integration/revisions_test.py
  conans/test/utils/tools.py
Labels: stage: review

#4233 Feature: initial Visual Studio 2019 (16) support
  conans/client/build/cmake_flags.py
  conans/client/conf/__init__.py
  conans/client/tools/win.py
  conans/test/unittests/client/build/msbuild_test.py
  conans/test/unittests/model/info/vs_toolset_compatible_test.py
  conans/test/unittests/util/msvs_toolset_test.py
Labels: stage: review

#4665 fix migration
  conans/client/migrations.py
Labels: stage: review

#4613 Add output argument to msbuild_command tool
  conans/client/tools/win.py
  conans/tools.py
Labels: stage: review

#4656 JSON output for create and install commands with multi_config cpp_info
  conans/client/conan_command_output.py
  conans/client/recorder/action_recorder.py
  conans/test/functional/command/json_output_test.py
Labels: stage: review

#4514 New graph resolution detects build_requires transitive conflicts
  conans/client/graph/graph.py
  conans/client/graph/graph_binaries.py
  conans/client/graph/graph_builder.py
  conans/client/graph/graph_manager.py
  conans/client/installer.py
  conans/model/options.py
  conans/model/requires.py
  conans/test/functional/graph/graph_manager_test.py
  conans/test/functional/graph/loop_detection_test.py
  conans/test/utils/conanfile.py
Labels: stage: review

#4644 config of package_id default mode
  conans/client/conf/__init__.py
  conans/client/graph/graph_binaries.py
  conans/model/info.py
  conans/test/functional/graph/graph_manager_base.py
  conans/test/functional/graph/package_id_modes_test.py
  conans/test/integration/build_id_test.py
  conans/test/unittests/model/transitive_reqs_test.py
Labels: stage: review

#4667 Add revision to ref in the install json output
  conans/client/cmd/export.py
  conans/client/conan_api.py
  conans/client/recorder/action_recorder.py
  conans/model/ref.py
  conans/test/functional/command/export_pkg_test.py
  conans/test/functional/command/json_output_test.py
  conans/test/integration/revisions_test.py
  conans/test/unittests/client/recorder/action_recorder_test.py
Labels: stage: review

#4669 fixing module.__file__ is None in py3
  conans/client/hook_manager.py
  conans/client/loader.py
  conans/test/unittests/client/conanfile_loader_test.py
Labels: stage: review

#4703 Exclude known pattern files from the upload
  conans/model/manifest.py
Labels: stage: review

#4660 python requires updates
  conans/client/conan_api.py
  conans/client/graph/python_requires.py
  conans/test/functional/python_requires/python_requires_test.py
Labels: stage: review

#4716 cppflags -> cxxflags (avoid using deprecated function)
  conans/client/build/autotools_environment.py
  conans/client/build/visual_environment.py
  conans/client/generators/b2.py
  conans/client/generators/boostbuild.py
  conans/client/generators/cmake.py
  conans/client/generators/cmake_common.py
  conans/client/generators/cmake_find_package.py
  conans/client/generators/cmake_multi.py
  conans/client/generators/compiler_args.py
  conans/client/generators/json_generator.py
  conans/client/generators/make.py
  conans/client/generators/pkg_config.py
  conans/client/generators/premake.py
  conans/client/generators/qbs.py
  conans/client/generators/qmake.py
  conans/client/generators/scons.py
  conans/client/generators/text.py
  conans/client/generators/visualstudio.py
  conans/client/generators/visualstudiolegacy.py
  conans/client/generators/xcode.py
  conans/client/generators/ycm.py
  conans/test/functional/build_helpers/autotools_environment_test.py
  conans/test/functional/build_helpers/cmake_flags_test.py
  conans/test/functional/build_helpers/visual_environment_test.py
  conans/test/functional/command/source_test.py
  conans/test/functional/generators/cmake_find_package_test.py
  conans/test/functional/generators/xcode_gcc_vs_test.py
  conans/test/functional/old/compile_helpers_test.py
  conans/test/functional/old/folders_access_test.py
  conans/test/unittests/client/build/autotools_environment_test.py
  conans/test/unittests/client/generators/b2_test.py
  conans/test/unittests/client/generators/boost_build_test.py
  conans/test/unittests/client/generators/cmake_test.py
  conans/test/unittests/client/generators/compiler_args_test.py
  conans/test/unittests/client/generators/json_test.py
  conans/test/unittests/client/generators/make_test.py
  conans/test/unittests/client/generators/pkg_config_test.py
  conans/test/unittests/client/generators/premake_test.py
  conans/test/unittests/client/generators/text_test.py
  conans/test/unittests/model/build_info/__init__.py
  conans/test/unittests/model/build_info/cppflags_test.py
  conans/test/unittests/model/build_info_test.py
  conans/test/utils/conanfile.py
Labels: stage: review

#4726 Replace py2/3 deprecated test functions: 'assertRaisesRegexp' and 'assertRegexpMatches' by 'six' implementation
  conans/test/functional/command/remove_test.py
  conans/test/functional/command/source_test.py
  conans/test/functional/command/upload_complete_test.py
  conans/test/functional/configuration/registry_test.py
  conans/test/functional/graph/graph_manager_test.py
  conans/test/functional/hooks/test_post_export.py
  conans/test/functional/old/compile_helpers_test.py
  conans/test/functional/old/requester_test.py
  conans/test/functional/workspace/workspace_test.py
  conans/test/integration/system_reqs_test.py
  conans/test/integration/test_build_info_extraction.py
  conans/test/unittests/client/build/cmake_test.py
  conans/test/unittests/client/build/meson_test.py
  conans/test/unittests/client/build/msbuild_test.py
  conans/test/unittests/client/conanfile_loader_test.py
  conans/test/unittests/client/conf/config_installer_test.py
  conans/test/unittests/client/graph/build_mode_test.py
  conans/test/unittests/client/graph/version_ranges_graph_test.py
  conans/test/unittests/client/hook_manager_test.py
  conans/test/unittests/client/profile_loader_test.py
  conans/test/unittests/client/tools/net_test.py
  conans/test/unittests/model/editable_layout/load_data_test.py
  conans/test/unittests/model/options_test.py
  conans/test/unittests/model/ref_test.py
  conans/test/unittests/model/settings_test.py
  conans/test/unittests/model/transitive_reqs_test.py
  conans/test/unittests/search/search_query_parse_test.py
  conans/test/unittests/server/conan_server_config_parser_test.py
  conans/test/unittests/server/conf_test.py
  conans/test/unittests/util/file_hashes_test.py
  conans/test/unittests/util/files/test_remove.py
  conans/test/unittests/util/output_test.py
  conans/test/unittests/util/tools_test.py
  conans/test/unittests/util/xz_test.py
Labels: stage: review

#4713 Exclude tests from distribution
  setup.py
Labels: stage: review

#4737 fix graph computation
  conans/client/graph/graph_builder.py
  conans/client/graph/graph_manager.py
  conans/test/functional/graph/graph_manager_test.py
  conans/test/functional/graph/transitive_deps_test.py
  conans/test/functional/workspace/workspace_test.py
Labels: stage: review

#4719 Added CONAN_XXX_ROOT variables to cmake_paths generator
  conans/client/generators/cmake_paths.py
  conans/test/functional/generators/cmake_paths_test.py
  conans/test/unittests/client/generators/cmake_paths_test.py
Labels: stage: review

#4750 Fix/test utils used in external projects
  conans/test/unittests/client/optimize_conanfile_load_test.py
  setup.py
Labels: stage: review

#4761 Collect libs uses sorted list (#4542)
  conans/client/tools/files.py
  conans/test/unittests/util/tools_test.py
Labels: stage: review

#4548 warnings as errors
  conans/client/tools/scm.py
  conans/client/tools/win.py
  conans/model/editable_layout.py
  conans/model/env_info.py
  conans/server/rest/bottle_plugins/authorization_header.py
  conans/test/__init__.py
  conans/test/integration/syncronize_test.py
  conans/test/unittests/model/build_info/cppflags_test.py
  conans/test/unittests/model/profile_test.py
  conans/test/unittests/util/build_sln_command_test.py
  conans/test/unittests/util/output_test.py
  conans/test/unittests/util/tools_test.py
  conans/test/unittests/util/vcvars_arch_test.py
  conans/test/unittests/util/vcvars_clangcl_test.py
  conans/test/unittests/util/vcvars_env_test.py
  conans/test/unittests/util/vcvars_store_test.py
  conans/test/unittests/util/xz_test.py
  conans/test/unittests/util/zip_permissions_test.py
  conans/util/files.py
  conans/util/windows.py
Labels: stage: review

#4708 Fix: add support for CMake generator platform
  conans/client/build/cmake.py
  conans/client/build/cmake_flags.py
  conans/client/conf/__init__.py
  conans/test/unittests/client/build/cmake_test.py
Labels: stage: review

#4764 Show warning if repo is not pristine when using SCM for revision
  conans/client/cmd/export.py
  conans/test/unittests/client/cmd/export/test_update_revision_in_metadata.py
Labels: stage: review

#4766 raise error instead of skipping files if short_paths
  conans/client/installer.py
  conans/client/tools/files.py
  conans/test/functional/old/path_limit_test.py
  conans/util/windows.py
Labels: stage: review

#4774 #4770 Do not force sudo when it is not found
  conans/client/tools/system_pm.py
  conans/test/unittests/util/tools_test.py
Labels: stage: review

#4780 Add output argument to 'vcvars_command' call from Meson helper
  conans/client/build/meson.py
Labels: priority: critical, stage: review, type: bug

#4709 supporting multiple conan-config-install and source/target subfolders
  conans/client/cache/cache.py
  conans/client/command.py
  conans/client/conan_api.py
  conans/client/conf/config_installer.py
  conans/client/migrations.py
  conans/test/functional/command/config_install_test.py
  conans/test/functional/old/test_migrations.py
  conans/test/unittests/client/conf/config_installer_test.py
Labels: stage: review

#4790 Bug with install update with build mode outdated
  conans/client/graph/graph_binaries.py
  conans/test/integration/install_outdated_test.py
Labels: stage: review

#4783 fix recursive build requires
  conans/client/graph/graph.py
  conans/client/graph/graph_builder.py
  conans/client/graph/graph_manager.py
  conans/model/workspace.py
  conans/test/functional/graph/graph_manager_base.py
  conans/test/functional/graph/graph_manager_test.py
  conans/test/functional/workspace/workspace_test.py
  conans/test/utils/conanfile.py
Labels: stage: review

#4794 Avoid running branch indexing builds
  .ci/jenkins/Jenkinsfile
Labels: stage: review

#4805 Look for vswhere in PATH when using tools.vswhere()
  conans/client/tools/win.py
  conans/test/unittests/util/tools_test.py
Labels: stage: review

#4657 Add configs to JSON generator
  conans/client/generators/json_generator.py
  conans/test/functional/generators/json_test.py
Labels: stage: review

#4767 Allow to specify revision_mode for each recipe
  conans/client/cmd/export.py
  conans/client/conan_api.py
  conans/model/conan_file.py
  conans/test/functional/command/export_test.py
  conans/test/functional/command/inspect_test.py
  conans/test/unittests/client/cmd/export/test_update_revision_in_metadata.py
Labels: stage: review

#4815 Review of vswhere PR #4805
  conans/client/tools/win.py
  conans/test/unittests/util/tools_test.py
Labels: stage: review

#4817 hotfix: graph fails if a package has several licenses
  conans/client/graph/grapher.py
  conans/test/functional/configuration/client_certs_test.py
Labels: stage: review

#4822 Update license date
  LICENSE.md
Labels: stage: review

#4662 Fix corrupted packages with missing conanmanifest.txt files
  conans/client/cmd/uploader.py
  conans/client/remote_manager.py
  conans/client/rest/rest_client_v1.py
  conans/client/rest/rest_client_v2.py
  conans/test/functional/command/upload_complete_test.py
  conans/test/functional/corrupted_packages_test.py
  conans/test/integration/install_update_test.py
Labels: stage: review, whiteboard

#4771 Add config variable 'general.error_on_override' (CONAN_ERROR_ON_OVERRIDE)
  conans/client/conf/__init__.py
  conans/model/requires.py
  conans/test/functional/graph/conflict_diamond_test.py
Labels: stage: review

#4748 avoiding double call to package() method
  conans/client/cmd/export.py
  conans/client/file_copier.py
  conans/client/importer.py
  conans/client/packager.py
  conans/test/functional/old/file_copier_test.py
  conans/test/functional/old/folders_access_test.py
Labels: stage: review

#4812 workspaces templates change to allow out-of-source builds
  conans/test/functional/workspace/workspace_test.py
  conans/util/templates.py
Labels: stage: review

#4834 Fix metadata not being updated for export-pkg --package-folder
  conans/client/cmd/export_pkg.py
  conans/test/functional/command/upload_test.py
Labels: stage: review, type: bug

#4830 Fix/scm no commit
  conans/client/cmd/export.py
  conans/client/tools/scm.py
  conans/test/integration/revisions_test.py
Labels: stage: review

#4838 Do not run 'export_sources' automatically for python_requires
  conans/client/source.py
  conans/test/functional/python_requires/python_requires_test.py
Labels: stage: review

#4835 Add env-var and config-var to explicitly set the cacert_path
  conans/client/cache/cache.py
  conans/client/conf/__init__.py
  conans/client/rest/conan_requester.py
  conans/paths/__init__.py
  conans/test/functional/configuration/requester_test.py
Labels: stage: review

#4824 Show profile name when detect a new one (#4818)
  conans/client/cache/cache.py
  conans/client/cmd/profile.py
  conans/client/conf/detect.py
  conans/test/functional/command/profile_test.py
  conans/test/integration/conf_default_settings_test.py
  conans/test/unittests/util/detect_test.py
Labels: stage: review

#4721 conan_basic_setup() same interface for cmake_multi
  conans/client/generators/cmake_common.py
  conans/test/functional/generators/cmake_multi_test.py
  conans/test/unittests/client/generators/cmake_test.py
Labels: stage: review

#4300 Feature: support N configs -> 1 package scheme for Visual Studio generator
  conans/client/generators/visualstudio.py
  conans/test/functional/generators/visual_studio_multi_test.py
  conans/test/unittests/client/generators/visual_studio_test.py
Labels: stage: review

#4849 Fix/cmake paths
  conans/client/generators/cmake_paths.py
  conans/test/functional/generators/cmake_paths_test.py
Labels: stage: review

#4841 Fix/warnings pattern
  conans/test/__init__.py
  conans/test/functional/command/config_install_test.py
  conans/test/functional/graph/graph_manager_test.py
  conans/test/integration/revisions_test.py
  conans/test/unittests/client/generators/cmake_paths_test.py
Labels: stage: review

#4714 cmake_find_package_multi
  conans/client/build/cmake.py
  conans/client/build/cmake_flags.py
  conans/client/generators/__init__.py
  conans/client/generators/cmake_find_package.py
  conans/client/generators/cmake_find_package_common.py
  conans/client/generators/cmake_find_package_multi.py
  conans/test/functional/generators/assets/cmake_find_package_multi/bye/conanfile.py
  conans/test/functional/generators/assets/cmake_find_package_multi/bye/src/CMakeLists.txt
  conans/test/functional/generators/assets/cmake_find_package_multi/bye/src/bye.cpp
  conans/test/functional/generators/assets/cmake_find_package_multi/bye/src/bye.h
  conans/test/functional/generators/assets/cmake_find_package_multi/hello/conanfile.py
  conans/test/functional/generators/assets/cmake_find_package_multi/hello/src/CMakeLists.txt
  conans/test/functional/generators/assets/cmake_find_package_multi/hello/src/hello.cpp
  conans/test/functional/generators/assets/cmake_find_package_multi/hello/src/hello.h
  conans/test/functional/generators/assets/cmake_find_package_multi/project_targets/CMakeLists.txt
  conans/test/functional/generators/cmake_find_package_multi_test.py
  conans/test/utils/tools.py
Labels: stage: review

#4854 Feature/replace check output
  conans/client/tools/oss.py
  conans/client/tools/scm.py
Labels: stage: review

#4857 Fix upload return codes
  conans/client/rest/uploader_downloader.py
  conans/test/unittests/client/rest/uploader_test.py
Labels: stage: review

#4858 improve output for v2 and revisions
  conans/client/cmd/export_pkg.py
  conans/client/graph/proxy.py
  conans/client/installer.py
  conans/client/remote_manager.py
  conans/client/rest/rest_client_v2.py
Labels: stage: review

#4865 CI run linux first
  .ci/jenkins/Jenkinsfile
Labels: stage: review

#4869 Print a message for unknown errors building the API and collaborators
  conans/client/command.py
  conans/client/conan_api.py
  conans/errors.py
Labels: stage: review
