Repository conan-io/conan, pull requests merged in 2019-05, with the labels that each got.

#5078 Fix: MSYS 3.x detection
  conans/client/tools/oss.py
  conans/test/unittests/client/tools/os_info/osinfo_test.py
Labels: stage: review

#5070 fix for editable declaring build_folder
  conans/client/installer.py
  conans/client/manager.py
  conans/test/functional/editable/layouts_test.py
  conans/test/utils/tools.py
Labels: stage: review

#5085 hardcoding VS 2017 in tests
  conans/test/functional/build_helpers/cmake_flags_test.py
  conans/test/functional/generators/cmake_skip_rpath_test.py
Labels: stage: review

#5073 Remove sudo from Travis template
  conans/client/cmd/new_ci.py
Labels: stage: review

#5086 test for hooks in conan.conf config-install
  conans/test/functional/command/config_install_test.py
Labels: stage: review

#5069 Use conan-io/hello example for the new command
  conans/client/cmd/new.py
  conans/test/integration/devflow_test.py
Labels: stage: review

#5088 upload --force uploads package always
  conans/client/cmd/uploader.py
  conans/test/functional/command/upload_test.py
  conans/test/integration/revisions_test.py
  conans/test/utils/tools.py
Labels: stage: review

#5092 Better error message to show usage of CONAN_SKIP_BROKEN_SYMLINKS_CHECK
  conans/model/manifest.py
Labels: stage: review

#4917 Add cppstd as a subsetting of compiler
  conans/client/build/autotools_environment.py
  conans/client/build/cmake_flags.py
  conans/client/build/cppstd_flags.py
  conans/client/build/meson.py
  conans/client/build/visual_environment.py
  conans/client/conan_api.py
  conans/client/conf/__init__.py
  conans/client/generators/compiler_args.py
  conans/client/settings_preprocessor.py
  conans/client/tools/system_pm.py
  conans/model/conan_file.py
  conans/model/info.py
  conans/model/profile.py
  conans/test/functional/build_helpers/cmake_flags_test.py
  conans/test/functional/build_helpers/msbuild_test.py
  conans/test/functional/cppstd/compiler_cppstd_test.py
  conans/test/functional/cppstd/default_cppstd_test.py
  conans/test/integration/basic_build_test.py
  conans/test/integration/cppstd_test.py
  conans/test/integration/package_id_test.py
  conans/test/unittests/client/generators/cmake_paths_test.py
  conans/test/unittests/client/generators/cmake_test.py
  conans/test/unittests/client/profile_loader/__init__.py
  conans/test/unittests/client/profile_loader/compiler_cppstd_test.py
  conans/test/unittests/client/profile_loader/profile_loader_test.py
  conans/test/unittests/model/other_settings_test.py
  conans/test/utils/deprecation.py
Labels: stage: review, type: feature

#5106 fix migration test
  conans/__init__.py
  conans/client/migrations_settings.py
Labels: stage: review

#5103 fix migration
  conans/client/cache/remote_registry.py
  conans/client/migrations_settings.py
  conans/test/functional/configuration/registry_test.py
Labels: stage: review

#5112 add gcc versions 8.3, 9.1
  conans/client/conf/__init__.py
Labels: stage: review

#5110 fix remote update --insert with same url
  conans/client/cache/remote_registry.py
  conans/test/functional/command/remote_test.py
Labels: stage: review

#5130 check raise migration compiler.cppstd failed
  conans/test/functional/old/test_migrations.py
  conans/test/unittests/client/profile_loader/compiler_cppstd_test.py
Labels: stage: review

#5150 fixing python_requires remotes commands
  conans/client/conan_api.py
  conans/test/functional/python_requires/python_requires_test.py
Labels: stage: review

#4896 Keep raw text in command description
  conans/client/command.py
Labels: stage: review, type: ux

#4984 Retry upload or download for error in response message
  conans/client/rest/uploader_downloader.py
  conans/test/functional/remote/retry_test.py
  conans/test/utils/tools.py
Labels: stage: review

#5029 Use 'revision' as the SVN's 'peg_revision' (broken for an edge case)
  conans/client/tools/scm.py
  conans/test/functional/scm/issues/__init__.py
  conans/test/functional/scm/issues/test_svn_tag.py
Labels: stage: review

#5102 #5101 Export detected_os from OSS Tools
  conans/test/unittests/client/conf/detect/detected_os_test.py
  conans/tools.py
Labels: stage: review

#5156 Feature: Support yaml list as workspace root.
  conans/model/workspace.py
  conans/test/functional/workspace/workspace_test.py
Labels: contributor pr, stage: review

#4923 Extended conan.conf syntax to permit host-specific proxies
  conans/client/conf/__init__.py
  conans/requirements.txt
  conans/test/functional/configuration/proxies_conf_test.py
Labels: stage: review

#4655 adding the env-var
  conans/client/build/visual_environment.py
  conans/client/generators/virtualbuildenv.py
  conans/test/functional/build_helpers/visual_environment_test.py
  conans/test/functional/generators/virtualbuildenv_test.py
Labels: stage: review

#4297 Feature: QNX Neutrino support
  conans/client/build/cmake_flags.py
  conans/client/build/compiler_flags.py
  conans/client/conf/__init__.py
  conans/client/tools/oss.py
  conans/test/unittests/client/build/compiler_flags_test.py
  conans/test/unittests/model/other_settings_test.py
  conans/test/unittests/model/transitive_reqs_test.py
  conans/test/unittests/util/tools_test.py
Labels: stage: review, type: look into

#5176 Feature/remove sys reqs wildcard
  conans/client/command.py
  conans/client/conan_api.py
  conans/test/integration/system_reqs_test.py
Labels: stage: review

#5236 Use string as reference for the Conan API
  conans/client/command.py
  conans/client/conan_api.py
  conans/test/integration/system_reqs_test.py
Labels: stage: review

#4340 Refactor local workflow: export and export_sources order
  conans/client/conan_api.py
  conans/client/source.py
  conans/test/functional/python_requires/python_requires_test.py
Labels: stage: review, type: engineering, whiteboard

#4538 Pass ANDROID_ABI & ANDROID_NDK to cmake
  conans/client/build/cmake_flags.py
  conans/client/conf/__init__.py
  conans/client/tools/__init__.py
  conans/client/tools/android.py
  conans/test/unittests/client/build/cmake_test.py
  conans/test/unittests/util/android_test.py
  conans/tools.py
Labels: stage: review

#5252 Unify multi remote test and moved them to functional
  conans/test/functional/remote/multi_remote_test.py
  conans/test/integration/multi_remotes_test.py
Labels: stage: review

#5261 Review Android CMake flags
  conans/client/build/cmake_flags.py
  conans/client/tools/__init__.py
  conans/client/tools/android.py
  conans/test/unittests/client/build/cmake_test.py
  conans/test/unittests/util/android_test.py
Labels: stage: review
