Repository conan-io/conan, pull requests merged in 2019-04, with the labels that each got.

#4870 Fix/migrate config install
  conans/client/migrations.py
Labels: stage: review

#4872 fix credentials necessary for install
  conans/client/cmd/uploader.py
  conans/client/remote_manager.py
  conans/client/rest/auth_manager.py
  conans/client/rest/rest_client_common.py
  conans/test/functional/command/install_test.py
Labels: stage: review

#4820 Feature/remove simple paths
  conans/client/cache/cache.py
  conans/client/conan_api.py
  conans/client/conan_command_output.py
  conans/client/conf/__init__.py
  conans/client/installer.py
  conans/client/manifest_manager.py
  conans/client/migrations.py
  conans/client/remote_manager.py
  conans/client/remover.py
  conans/paths/__init__.py
  conans/paths/package_layouts/package_cache_layout.py
  conans/paths/package_layouts/package_editable_layout.py
  conans/paths/simple_paths.py
  conans/search/search.py
  conans/server/conf/__init__.py
  conans/server/conf/default_server_conf.py
  conans/server/launcher.py
  conans/server/migrate.py
  conans/server/store/disk_adapter.py
  conans/server/store/server_store.py
  conans/test/functional/command/config_test.py
  conans/test/functional/command/download_test.py
  conans/test/functional/command/install_test.py
  conans/test/functional/command/upload_complete_test.py
  conans/test/functional/editable/graph_related_test.py
  conans/test/functional/graph/graph_manager_base.py
  conans/test/functional/old/package_copier_test.py
  conans/test/functional/old/package_integrity_test.py
  conans/test/functional/old/paths_test.py
  conans/test/functional/old/short_paths_test.py
  conans/test/functional/remote/rest_api_test.py
  conans/test/integration/case_sensitive_test.py
  conans/test/integration/conf_default_settings_test.py
  conans/test/integration/manifest_validation_test.py
  conans/test/integration/system_reqs_test.py
  conans/test/unittests/client/cache_test.py
  conans/test/unittests/client/graph/version_ranges_graph_test.py
  conans/test/unittests/model/fake_retriever.py
  conans/test/unittests/model/transitive_reqs_test.py
  conans/test/unittests/search/disk_search_test.py
  conans/test/unittests/server/service/service_test.py
  conans/test/utils/server_launcher.py
  conans/test/utils/tools.py
  conans/util/windows.py
Labels: stage: review

#4274 Some docstrings for version class
  conans/model/version.py
  conans/test/unittests/model/version_test.py
Labels: stage: review

#4888 More meaningfull error when remote failure
  conans/client/graph/graph_binaries.py
  conans/test/integration/install_update_test.py
Labels: stage: review

#4894 Capture NotFoundError due to missing python_requires
  conans/client/graph/python_requires.py
  conans/client/loader.py
  conans/test/functional/command/inspect_test.py
Labels: stage: review

#4927 adding assert for #4898
  conans/client/graph/graph_binaries.py
Labels: stage: review

#4724 Feature/remotes to metadata
  conans/client/cache/cache.py
  conans/client/cache/remote_registry.py
  conans/client/cmd/copy.py
  conans/client/cmd/create.py
  conans/client/cmd/download.py
  conans/client/cmd/export_pkg.py
  conans/client/cmd/search.py
  conans/client/cmd/test.py
  conans/client/cmd/uploader.py
  conans/client/conan_api.py
  conans/client/conan_command_output.py
  conans/client/conf/config_installer.py
  conans/client/graph/graph_binaries.py
  conans/client/graph/graph_builder.py
  conans/client/graph/graph_manager.py
  conans/client/graph/proxy.py
  conans/client/graph/python_requires.py
  conans/client/graph/range_resolver.py
  conans/client/installer.py
  conans/client/manager.py
  conans/client/migrations.py
  conans/client/remover.py
  conans/client/source.py
  conans/model/package_metadata.py
  conans/paths/package_layouts/package_cache_layout.py
  conans/test/functional/command/config_install_test.py
  conans/test/functional/command/install_test.py
  conans/test/functional/command/remote_test.py
  conans/test/functional/command/remove_test.py
  conans/test/functional/command/search_test.py
  conans/test/functional/configuration/registry_test.py
  conans/test/functional/editable/graph_related_test.py
  conans/test/functional/graph/graph_manager_base.py
  conans/test/functional/graph/graph_manager_test.py
  conans/test/functional/old/download_test.py
  conans/test/integration/multi_remote_test.py
  conans/test/integration/revisions_test.py
  conans/test/unittests/client/graph/version_ranges_graph_test.py
  conans/test/unittests/model/transitive_reqs_test.py
  conans/test/utils/tools.py
Labels: stage: review

#4934 new full metadata revision migration
  conans/client/migrations.py
  conans/test/functional/old/test_migrations.py
Labels: stage: review

#4890 Use our own 'check_output' to capture output
  conans/client/tools/apple.py
  conans/client/tools/oss.py
  conans/client/tools/pkg_config.py
  conans/client/tools/scm.py
  conans/client/tools/win.py
  conans/test/functional/command/info_folders_test.py
  conans/test/functional/generators/virtualbuildenv_test.py
  conans/test/integration/run_envronment_test.py
  conans/test/unittests/client/tools/os_info/osinfo_test.py
  conans/test/unittests/util/detect_test.py
  conans/test/unittests/util/tools_test.py
  conans/test/utils/tools.py
Labels: stage: review

#4883 unzip with gz too
  conans/client/tools/files.py
  conans/test/unittests/util/tools_test.py
Labels: stage: review

#4944 Update README.rst
  README.rst
Labels: stage: review

#4941 Default filename for workspaces: conanws.yml (used in install command)
  conans/client/command.py
  conans/model/workspace.py
  conans/test/functional/workspace/workspace_test.py
Labels: stage: review

#4903 Add argument '--raw' to command inspect, more machine friendly
  conans/client/command.py
  conans/client/printer.py
  conans/test/functional/command/inspect_test.py
Labels: stage: review

#4948 Fix wrong error message
  conans/client/remover.py
  conans/test/functional/editable/forbidden_commands_test.py
Labels: stage: review

#4950 Add metaclass in a py2/3 compatible way
  conans/model/conan_generator.py
  conans/server/rest/bottle_plugins/authorization_header.py
  conans/server/service/authorize.py
Labels: stage: review

#4955 Output is dict as string, no order guaranteed, so convert to dict and compare
  conans/test/functional/command/inspect_test.py
Labels: stage: review

#4897 Improve export-pkg message, add a notice about provided package-folder
  conans/client/command.py
Labels: stage: review

#4945 testing updated Pyyaml
  conans/requirements.txt
Labels: stage: review

#4946 Unbuffered output in ConanRunner
  conans/client/runner.py
Labels: stage: review

#4823 [Feature] Add Windows CE support
  conans/client/build/autotools_environment.py
  conans/client/build/cmake_flags.py
  conans/client/build/msbuild.py
  conans/client/conf/__init__.py
  conans/client/generators/b2.py
  conans/client/tools/win.py
  conans/test/unittests/client/build/cmake_test.py
  conans/test/unittests/client/build/msbuild_test.py
  conans/test/unittests/model/other_settings_test.py
  conans/test/unittests/model/transitive_reqs_test.py
  conans/test/unittests/util/vcvars_arch_test.py
Labels: complex: medium, priority: medium, stage: queue, type: look into

#4979 fix local flow with python requires
  conans/client/conan_api.py
  conans/test/functional/python_requires/python_requires_test.py
Labels: stage: review, type: bug

#4989 test for build with debug using release deps
  conans/test/functional/command/build_test.py
Labels: stage: review

#4995 do not find modules for cmake_find_package_multi
  conans/client/generators/cmake_find_package.py
  conans/client/generators/cmake_find_package_multi.py
  conans/test/functional/generators/cmake_find_package_multi_test.py
Labels: stage: review

#5005 Add default_package_id_mode in the default conan.conf (#4974)
  conans/client/conf/__init__.py
  conans/test/functional/command/config_install_test.py
  conans/test/functional/graph/package_id_modes_test.py
Labels: stage: review

#4991 Skip symlink checks
  conans/client/conf/__init__.py
  conans/model/manifest.py
  conans/test/functional/configuration/skip_broken_symlinks.py
  conans/util/files.py
Labels: stage: review

#4976 refactor export for locks
  conans/client/cmd/export.py
  conans/client/conan_api.py
  conans/test/integration/devflow_test.py
Labels: stage: review

#5014 concurrent uploads checks and tests
  conans/client/cmd/uploader.py
  conans/test/functional/command/upload_test.py
Labels: stage: review

#4987 fixing transitive order of privates
  conans/client/graph/graph.py
  conans/client/graph/graph_binaries.py
  conans/client/graph/graph_builder.py
  conans/test/functional/graph/graph_manager_base.py
  conans/test/functional/graph/graph_manager_test.py
  conans/test/functional/graph/private_deps_test.py
  conans/test/utils/conanfile.py
Labels: stage: review

#5028 Fix/vs2019+ninja
  conans/client/build/cmake.py
  conans/client/build/cmake_flags.py
  conans/test/unittests/client/build/cmake_test.py
Labels: stage: review

#4963 Implement tools.Version (based on SemVer)
  conans/client/tools/version.py
  conans/test/unittests/client/tools/test_version.py
  conans/tools.py
Labels: stage: review

#5023 fixed broken test in py2-win, moved some tests
  conans/test/unittests/client/tools/scm/test_git.py
  conans/test/unittests/client/tools/scm/test_svn.py
  conans/test/unittests/client/tools/system_pm_test.py
  conans/test/unittests/util/tools_test.py
Labels: stage: review

#5032 Feature/artifactory testing
  conans/test/integration/revisions_test.py
  conans/test/utils/tools.py
Labels: stage: review

#4942 Up requirement 'parameterized' (this version adds 'parameterized_class' decorator)
  conans/requirements_dev.txt
Labels: stage: review

#4986 Add tests checking ID for different 'cppstd' strategies
  conans/test/functional/cppstd/__init__.py
  conans/test/functional/cppstd/default_cppstd_test.py
Labels: stage: review

#4346 Feature: add support for Emscripten (asm.js & wasm)
  conans/client/conf/__init__.py
  conans/client/tools/files.py
  conans/client/tools/oss.py
  conans/test/unittests/model/other_settings_test.py
  conans/test/unittests/model/transitive_reqs_test.py
  conans/test/unittests/util/tools_test.py
Labels: Feedback please!, stage: review, type: look into

#5003 try visual_studio generator with backslashes
  conans/client/generators/visualstudio.py
  conans/test/functional/generators/xcode_gcc_vs_test.py
  conans/test/unittests/client/generators/visual_studio_test.py
Labels: stage: review

#5042 Fix find_dependency NO_MODULE for cmake < 3.9
  conans/client/generators/cmake_find_package.py
Labels: stage: review

#4965 'tar_extract' function fails if there is a linked folder in workingdir that matches one in the tar file
  conans/test/unittests/util/files/tar_extract_test.py
  conans/util/files.py
Labels: stage: review

#5044 Feature/improve settings migration
  conans/client/migrations.py
  conans/client/migrations_settings.py
  conans/test/functional/old/test_migrations.py
Labels: stage: review

#4918 Always remove package folder in conan create
  conans/client/installer.py
  conans/test/functional/command/create_test.py
Labels: stage: review, type: bug

#5033 refactor layouts
  conans/client/cache/cache.py
  conans/client/cmd/copy.py
  conans/client/cmd/download.py
  conans/client/cmd/export_pkg.py
  conans/client/cmd/uploader.py
  conans/client/graph/graph_binaries.py
  conans/client/graph/proxy.py
  conans/client/installer.py
  conans/client/manifest_manager.py
  conans/client/remote_manager.py
  conans/client/source.py
  conans/test/functional/build_helpers/autotools_environment_test.py
  conans/test/functional/build_helpers/msbuild_test.py
  conans/test/functional/command/copy_packages_test.py
  conans/test/functional/command/download_test.py
  conans/test/functional/command/export_dirty_test.py
  conans/test/functional/command/export_path_test.py
  conans/test/functional/command/export_pkg_test.py
  conans/test/functional/command/export_test.py
  conans/test/functional/command/info_folders_test.py
  conans/test/functional/command/remove_test.py
  conans/test/functional/command/search_test.py
  conans/test/functional/command/upload_complete_test.py
  conans/test/functional/command/upload_test.py
  conans/test/functional/conanfile/no_copy_source_test.py
  conans/test/functional/environment/apply_environment_test.py
  conans/test/functional/generators/xcode_gcc_vs_test.py
  conans/test/functional/graph/graph_manager_base.py
  conans/test/functional/graph/transitive_deps_test.py
  conans/test/functional/old/conan_trace_file_test.py
  conans/test/functional/old/create_package_test.py
  conans/test/functional/old/package_copier_test.py
  conans/test/functional/old/path_limit_test.py
  conans/test/functional/old/paths_test.py
  conans/test/functional/old/remove_old_export_sources_layout_test.py
  conans/test/functional/old/rmdir_fail_test.py
  conans/test/functional/python_requires/python_requires_test.py
  conans/test/functional/remote/broken_download_test.py
  conans/test/functional/scm/scm_test.py
  conans/test/functional/tgz_macos_dot_files.py
  conans/test/integration/complete_test.py
  conans/test/integration/devflow_test.py
  conans/test/integration/export_sources_test.py
  conans/test/integration/go_complete_test.py
  conans/test/integration/hook_test.py
  conans/test/integration/install_outdated_test.py
  conans/test/integration/install_selected_packages_test.py
  conans/test/integration/install_update_test.py
  conans/test/integration/manifest_validation_test.py
  conans/test/integration/only_source_test.py
  conans/test/integration/package_id_test.py
  conans/test/integration/settings_override_test.py
  conans/test/integration/symlinks_test.py
  conans/test/integration/system_reqs_test.py
  conans/test/unittests/client/cache_test.py
  conans/test/utils/tools.py
Labels: stage: review

#4765 "ANY" is also matching "None" within settings
  conans/model/settings.py
  conans/test/unittests/model/settings_test.py
Labels: stage: review

#5052 MSBuild. parameter to skip toolset adjustement
  conans/client/build/msbuild.py
  conans/test/unittests/client/build/msbuild_test.py
Labels: stage: review

#4940 Add install folder to command 'conan workspace install'
  conans/client/command.py
  conans/client/conan_api.py
  conans/model/workspace.py
  conans/test/functional/workspace/workspace_test.py
Labels: stage: review

#4877 SCM commit message
  conans/client/tools/scm.py
  conans/test/unittests/client/tools/scm/test_git.py
  conans/test/unittests/client/tools/scm/test_svn.py
  conans/test/unittests/util/tools_test.py
Labels: stage: review

#4972 Built-in deploy generator
  conans/client/generators/__init__.py
  conans/client/generators/deploy.py
  conans/paths/__init__.py
  conans/test/functional/generators/deploy_test.py
  conans/test/utils/tools.py
Labels: stage: review

#5021 #4956 cmake_find_package_multi might need also CMAKE_MODULE_PATH
  conans/client/build/cmake_flags.py
  conans/test/unittests/client/generators/cmake_test.py
Labels: stage: review

#5057 setup description
  README.rst
  setup.py
Labels: stage: review

#4321 [python_requires] Directories 'exports' and 'exports_sources' are available through 'self.python_requires' object in consumer.
  conans/client/graph/printer.py
  conans/client/graph/python_requires.py
  conans/client/installer.py
  conans/client/loader.py
  conans/test/functional/python_requires/python_requires_test.py
  conans/test/functional/python_requires/test_export_sources.py
Labels: stage: review

#5053 Fix develop test: Adjusted vs environment before running cmake
  conans/test/functional/build_helpers/cmake_targets_test.py
Labels: stage: review

#5056 fixed problem with transitive build_requires
  conans/client/graph/graph_builder.py
  conans/test/functional/build_requires/build_requires_test.py
  conans/test/functional/graph/graph_manager_test.py
Labels: stage: review

#5065 Not fail touching
  conans/util/files.py
Labels: stage: review

#5064 Fixed 0 size and test
  conans/client/cmd/uploader.py
  conans/test/functional/configuration/compressed_symlinks_test.py
Labels: stage: review
