Repository conan-io/conan, pull requests merged in 2019-09, with the labels that each got.

#5729 [Fix] package_id should be used for 'recipe_revision_mode'
  conans/model/info.py
  conans/test/unittests/model/info_test.py
Labels: complex: low, priority: high, type: bug

#5466 Detect the number of CPUs used by Docker (#5464)
  conans/client/tools/oss.py
  conans/test/unittests/util/tools_test.py
Labels: stage: review

#5808 Lock buggy urllib3 versions only
  conans/requirements.txt
Labels: stage: review

#5806 app simplifying
  conans/client/conan_api.py
  conans/client/conf/config_installer.py
Labels: type: engineering

#5815 test client load() file method
  conans/test/functional/build_helpers/cmake_targets_test.py
  conans/test/functional/build_requires/build_requires_test.py
  conans/test/functional/command/alias_test.py
  conans/test/functional/command/build_test.py
  conans/test/functional/command/create_test.py
  conans/test/functional/command/export_pkg_test.py
  conans/test/functional/command/user_test.py
  conans/test/functional/conanfile/imports_tests.py
  conans/test/functional/editable/layouts_test.py
  conans/test/functional/generators/generators_test.py
  conans/test/functional/graph/private_deps_test.py
  conans/test/functional/graph/version_ranges_diamond_test.py
  conans/test/functional/graph_lock/graph_lock_test.py
  conans/test/functional/old/conanfile_extend_test.py
  conans/test/functional/old/libcxx_setting_test.py
  conans/test/functional/python_requires/python_package_reuse_test.py
  conans/test/integration/order_libs_test.py
  conans/test/integration/package_id_test.py
  conans/test/unittests/model/other_settings_test.py
  conans/test/utils/tools.py
Labels: type: engineering

#5820 Remove py34
  .travis.yml
  appveyor.yml
Labels: stage: review

#5552 Feature: support OSX frameworks
  conans/client/build/compiler_flags.py
  conans/client/generators/cmake.py
  conans/client/generators/cmake_common.py
  conans/client/generators/cmake_find_package_common.py
  conans/client/generators/compiler_args.py
  conans/client/generators/json_generator.py
  conans/client/generators/make.py
  conans/client/generators/pkg_config.py
  conans/client/generators/text.py
  conans/client/generators/xcode.py
  conans/client/run_environment.py
  conans/model/build_info.py
  conans/model/conan_file.py
  conans/model/editable_layout.py
  conans/test/functional/generators/cmake_find_package_test.py
  conans/test/functional/old/run_environment_test.py
  conans/test/unittests/client/generators/cmake_test.py
  conans/test/unittests/client/generators/compiler_args_test.py
  conans/test/unittests/client/generators/make_test.py
  conans/test/unittests/client/generators/pkg_config_test.py
Labels: stage: review
