Repository conan-io/conan, pull requests merged in 2019-12, with the labels that each got.

#6142 skip downloading call to to_file_bytes
  conans/client/rest/uploader_downloader.py
Labels: type: look into

#6109 Test remotes picked when doing a install with --update
  conans/test/functional/remote/multi_remote_test.py
Labels: stage: review

#6224 Refactor/graph builder
  conans/client/graph/graph_builder.py
  conans/test/functional/command/alias_test.py
Labels: stage: review

#6254 Use HttpBasic auth in the ping API endpoint for the "conan user" command.
  conans/client/rest/rest_client.py
  conans/client/rest/rest_client_common.py
  conans/test/functional/remote/auth_test.py
Labels: type: bug
