Repository conan-io/conan, pull requests merged in 2019-07, with the labels that each got.

#5215 Detect System package name by recipe settings (#5026)
  conans/client/tools/system_pm.py
  conans/test/unittests/client/tools/system_pm_test.py
Labels: stage: review

#5441 Fix verify_ssl field in SCM discarded when used with False value
  conans/model/scm.py
  conans/test/functional/scm/scm_test.py
Labels: stage: review

#5460 table html: fix Legend section
  conans/search/binary_html_table.py
Labels: type: bug

#5457 Pure refactor from PR #5289
  conans/client/build/cmake_flags.py
  conans/test/functional/build_helpers/cmake_flags_test.py
  conans/test/unittests/client/build/cmake_test.py
Labels: stage: review

#5459 [engineering] SCM discard empty string values
  conans/client/source.py
  conans/model/scm.py
Labels: stage: review, type: engineering

#5461 Do not raise when accessing the metadata of editable packages
  conans/client/cache/editable.py
  conans/client/cache/remote_registry.py
  conans/test/functional/command/remote_test.py
Labels: stage: review
