Repository conan-io/conan, pull requests merged in 2019-06, with the labels that each got.

#5294 Reorder functions in Workspace class
  conans/model/workspace.py
Labels: type: engineering

#3733 Refactorize the parser of cpp_info in TXTGenerator
  conans/client/generators/text.py
Labels: stage: review, type: engineering

#5293 P argument deprecation
  conans/client/command.py
  conans/client/conan_api.py
  conans/test/functional/command/copy_packages_test.py
  conans/test/functional/command/download_test.py
  conans/test/functional/command/upload_test.py
Labels: stage: review

#5375 Fix virtualenv constructor.
  conans/client/generators/virtualenv.py
Labels: stage: review
