Repository conan-io/conan, pull requests merged in 2019-10, with the labels that each got.

#5863 Use reference with recipe revision for build order
  conans/client/graph/graph.py
  conans/client/rest/client_routes.py
  conans/model/ref.py
  conans/test/functional/graph_lock/graph_lock_ci_test.py
  conans/test/integration/revisions_test.py
Labels: type: bug

#5880 Fix setting of server cached capabilities
  conans/client/rest/rest_client.py
  conans/test/functional/command/upload_test.py
Labels: type: bug

#5810 fixes None-None toolset referenced by b2 generator
  conans/client/generators/b2.py
  conans/test/unittests/client/generators/b2_test.py
Labels: stage: review

#5894 fixed bug in lockfiles for conanfile.txt
  conans/model/graph_lock.py
  conans/test/functional/graph_lock/graph_lock_test.py
Labels: stage: review

#5830 Add new interface for issues
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: stage: review

#5811 removed duplicated line in b2 output
  conans/client/generators/b2.py
  conans/test/unittests/client/generators/b2_test.py
Labels: stage: review

#4958 Feature/package id mode
  conans/client/conan_api.py
  conans/client/graph/graph_binaries.py
  conans/client/graph/graph_manager.py
  conans/client/installer.py
  conans/client/manager.py
  conans/model/graph_lock.py
  conans/model/options.py
  conans/test/functional/command/upload_test.py
  conans/test/functional/graph/full_revision_mode_test.py
  conans/test/functional/graph/graph_manager_base.py
  conans/test/functional/graph/package_id_modes_test.py
  conans/test/functional/graph_lock/graph_lock_ci_test.py
  conans/test/functional/graph_lock/graph_lock_test.py
Labels: stage: review

#5828 Rewrite VirtualEnvGenerator tests
  conans/test/functional/generators/virtualenv_test.py
  conans/test/integration/run_environment_test.py
  conans/test/integration/run_envronment_test.py
  conans/test/unittests/client/build/cmake_test.py
  conans/test/unittests/client/generators/virtualbuildenv_test.py
  conans/test/unittests/client/generators/virtualenv_test.py
  conans/test/unittests/client/generators/virtualrunenv_test.py
  conans/test/unittests/client/run_environment_test.py
  conans/test/utils/conanfile.py
Labels: stage: review, type: engineering

#5761 #5320 Import Python Patch
  conans/client/tools/files.py
  conans/requirements.txt
  conans/test/unittests/tools/files_patch_test.py
Labels: stage: review, type: look into

#5713 Override version ranges from downstream consumers
  conans/model/requires.py
  conans/test/functional/graph/version_range_error_test.py
  conans/test/functional/graph/version_range_override_test.py
  conans/test/unittests/client/graph/version_ranges_graph_test.py
Labels: stage: review

#5791 Add DnfTool for using dnf package manager
  conans/client/tools/oss.py
  conans/client/tools/system_pm.py
  conans/test/unittests/client/tools/system_pm_test.py
  conans/tools.py
Labels: complex: low, priority: low, stage: review
