Repository conan-io/conan, pull requests merged in 2020-03, with the labels that each got.

#6602 [refact] Run 'conanfile::build()' only once in the sources
  conans/client/build/build.py
  conans/client/cmd/build.py
  conans/client/installer.py
  conans/test/functional/options/options_test.py
  conans/test/unittests/tools/files_patch_test.py
Labels: type: engineering

#6549 Only append generator_platform if needed
  conans/client/build/cmake.py
  conans/test/unittests/client/build/cmake_test.py
Labels: complex: low, component: Build, priority: high, stage: queue, type: bug

#5592 [1/n] [xbuild] Add support for crossbuilding into the graph
  conans/client/conan_command_output.py
  conans/client/graph/graph.py
  conans/client/graph/graph_builder.py
  conans/client/graph/graph_manager.py
  conans/client/graph/grapher.py
  conans/client/graph/printer.py
  conans/client/installer.py
  conans/model/conan_file.py
  conans/model/graph_info.py
  conans/model/graph_lock.py
  conans/model/requires.py
  conans/test/functional/cross_building/__init__.py
  conans/test/functional/cross_building/graph/__init__.py
  conans/test/functional/cross_building/graph/_base_test_case.py
  conans/test/functional/cross_building/graph/breq_of_breq_test.py
  conans/test/functional/cross_building/graph/build_requires_in_profile_test.py
  conans/test/functional/cross_building/graph/build_requires_in_recipe_test.py
  conans/test/functional/cross_building/graph/no_way_back_to_host_test.py
  conans/test/functional/cross_building/graph/protobuf_test.py
  conans/test/functional/cross_building/graph/protoc_basic_test.py
  conans/test/functional/cross_building/graph/protoc_with_gtest_test.py
  conans/test/functional/graph/graph_manager_base.py
  conans/test/functional/graph/graph_manager_test.py
  conans/test/unittests/client/conanfile_loader_test.py
  conans/test/unittests/client/graph/deps_graph_test.py
  conans/test/unittests/client/graph/version_ranges_graph_test.py
  conans/test/unittests/model/fake_retriever.py
  conans/test/unittests/model/transitive_reqs_test.py
Labels: stage: review
