Repository conan-io/conan, pull requests merged in 2020-11, with the labels that each got.

#8070 keep python files in packaging .pyc, .pyo, etc
  conans/client/conf/__init__.py
  conans/model/manifest.py
  conans/paths/package_layouts/package_cache_layout.py
  conans/test/test_package_python_files.py
Labels: type: feature

#8115 [refact] Use downloaders via a 'run_downloader' function
  conans/client/downloaders/__init__.py
  conans/client/downloaders/cached_file_downloader.py
  conans/client/downloaders/download.py
  conans/client/downloaders/file_downloader.py
  conans/client/rest/rest_client_v1.py
  conans/client/rest/rest_client_v2.py
  conans/client/tools/net.py
  conans/test/functional/cache/download_cache_test.py
  conans/test/functional/command/config_install_test.py
  conans/test/unittests/client/rest/downloader_test.py
Labels: type: engineering

#8094 add --no-remote to list references without remote
  conans/client/command.py
  conans/client/conan_api.py
  conans/test/functional/remote/multi_remote_test.py
Labels: type: look into
