Repository conan-io/conan, pull requests merged in 2020-07, with the labels that each got.

#7276 [cpp_info] [refact] Do not assign to 'xxxx_paths' fields
  conans/client/build/autotools_environment.py
  conans/test/functional/command/test_package_test.py
  conans/test/functional/cross_building/graph/protobuf_test.py
  conans/test/functional/graph/diamond_test.py
  conans/test/functional/graph/graph_manager_base.py
  conans/test/functional/graph/graph_manager_test.py
  conans/test/integration/package_info_test.py
  conans/test/unittests/client/generators/b2_test.py
  conans/test/unittests/client/generators/boost_build_test.py
  conans/test/unittests/client/generators/cmake_test.py
  conans/test/unittests/client/generators/compiler_args_test.py
  conans/test/unittests/model/build_info/components_test.py
  conans/test/unittests/model/build_info/deps_cpp_info_test.py
  conans/test/unittests/model/build_info_test.py
Labels: type: engineering

#7277 [cpp_info] [refact] Rewrite text generator parser
  conans/client/generators/b2.py
  conans/client/generators/text.py
  conans/model/build_info.py
  conans/test/functional/command/build_test.py
  conans/test/functional/command/test_package_test.py
  conans/test/unittests/client/generators/text_test.py
  conans/test/unittests/model/build_info_test.py
Labels: type: engineering

#7359 conditional generators test with configure()
  conans/test/functional/generators/generators_test.py
Labels: type: look into

#7360 Feature/min conan version
  conans/client/conf/required_version.py
  conans/client/loader.py
  conans/client/tools/version.py
  conans/test/functional/conanfile/required_conan_version_test.py
  conans/test/functional/configuration/required_version_test.py
Labels: Feedback please!

#7167 Improve '--update' docstring
  conans/client/command.py
Labels: component: ux

#5705 Feature: add settings for clang-cl (clang on Windows)
  conans/client/conf/__init__.py
Labels: type: look into
