Repository conan-io/conan, pull requests merged in 2020-02, with the labels that each got.

#6000 Meson build helper: make sure env variables from conan profile take precedence
  conans/client/build/cmake.py
  conans/client/build/meson.py
  conans/client/tools/env.py
  conans/test/functional/build_helpers/cmake_flags_test.py
  conans/test/functional/build_helpers/meson_test.py
  conans/test/unittests/client/build/cmake_test.py
  conans/test/unittests/util/tools_test.py
Labels: type: look into

#6265 Add quotes to virtualenv template
  conans/client/generators/virtualenv.py
  conans/test/functional/generators/virtualenv_test.py
Labels: stage: review, type: bug

#6550 Restructure BinaryInstaller to raise first if missing, then do all downloads
  conans/client/graph/graph_binaries.py
  conans/client/installer.py
Labels: type: engineering

#6518 cmake_find_package - CONAN_FOUND_LIBRARY shouldn't be visible in cmake-gui
  conans/client/generators/cmake_common.py
  conans/client/generators/cmake_find_package_common.py
Labels: type: ux

#6492 [ci] Set the value of 'general.revisions_enabled' only if given
  conans/test/utils/tools.py
Labels: component: CI
