Repository conan-io/conan, pull requests merged in 2022-03, with the labels that each got.

#10495 Feature/develop2 lockfile override
  conans/cli/commands/build.py
  conans/cli/commands/create.py
  conans/cli/commands/export.py
  conans/cli/commands/export_pkg.py
  conans/cli/commands/graph.py
  conans/cli/commands/install.py
  conans/cli/commands/lock.py
  conans/cli/commands/test.py
  conans/cli/common.py
  conans/model/graph_lock.py
  conans/test/integration/lockfile/test_lock_requires.py
  conans/test/integration/lockfile/test_lock_requires_revisions.py
Labels: type: look into

#10755 msvc runtime to AutotoolsToolchain
  conan/tools/gnu/autotoolstoolchain.py
  conans/test/unittests/tools/gnu/autotoolschain_test.py
Labels: type: bug

#10677 Feature/profile include priority
  conans/test/integration/configuration/test_profile_priority.py
Labels: type: look into

#10794 remove UserInfo, use ``conf_info`` instead
  conans/client/installer.py
  conans/model/conanfile_interface.py
  conans/model/user_info.py
  conans/test/integration/conanfile/folders_access_test.py
  conans/test/integration/conanfile/user_info_test.py
  conans/test/integration/configuration/conf/test_conf_from_br.py
  conans/test/integration/cross_building/user_info_test.py
Labels: type: look into

#10091 changed cwd for source() method
  conans/client/source.py
  conans/test/functional/test_third_party_patch_flow.py
  conans/test/functional/tools/test_files.py
Labels: type: look into

#10800 [conf] Global flags management
  conan/tools/cmake/toolchain/blocks.py
  conan/tools/cmake/toolchain/toolchain.py
  conan/tools/gnu/autotoolstoolchain.py
  conan/tools/meson/meson.py
  conan/tools/meson/toolchain.py
  conans/model/conf.py
  conans/test/integration/toolchains/cmake/test_cmaketoolchain.py
  conans/test/integration/toolchains/gnu/__init__.py
  conans/test/integration/toolchains/gnu/test_autotoolstoolchain.py
  conans/test/integration/toolchains/meson/test_mesontoolchain.py
  conans/test/unittests/client/toolchain/autotools/autotools_toolchain_test.py
  conans/test/unittests/model/test_conf.py
Labels: type: feature

#10868 backport of compatibility() recipe method
  conans/client/graph/compatibility.py
  conans/client/graph/graph_binaries.py
  conans/model/values.py
  conans/test/integration/package_id/compatible_test.py
Labels: type: look into
