Repository conan-io/conan, pull requests merged in 2022-07, with the labels that each got.

#11585 Feature : provide Path accesssors
  conans/client/loader.py
  conans/model/conan_file.py
  conans/model/conanfile_interface.py
  conans/test/integration/conanfile/folders_access_test.py
Labels: type: look into

#11493 test for download with python-requires in another repo
  conans/test/integration/command/download/download_test.py
Labels: type: look into

#11610 11080: Add tools for checking max cppstd version
  conan/tools/build/__init__.py
  conan/tools/build/cppstd.py
  conans/test/unittests/client/tools/cppstd_required_test.py
  conans/test/utils/mocks.py
Labels: stage: review

#11678 AutotoolsToolchain: empty None values from self fields + Refactor
  conan/tools/gnu/autotoolstoolchain.py
  conans/test/integration/toolchains/gnu/test_autotoolstoolchain.py
  conans/test/unittests/client/toolchain/autotools/autotools_toolchain_test.py
Labels: type: bug, type: feature

#11441 [develop2] Let dependency define package_id modes
  conans/client/graph/compute_pid.py
  conans/model/requires.py
  conans/test/integration/package_id/package_id_modes_test.py
Labels: type: feature
