Repository conan-io/conan, pull requests merged in 2022-11, with the labels that each got.

#12378 [develop2] Simplifying compress/uncompress
  conans/client/cmd/uploader.py
  conans/client/remote_manager.py
  conans/test/unittests/client/util/files_test.py
  conans/util/files.py
Labels: type: look into

#12539 [develop2] New proposal for cppstd validate/validate_build
  conans/client/graph/compatibility.py
  conans/client/graph/compute_pid.py
  conans/client/graph/graph_binaries.py
  conans/client/graph/install_graph.py
  conans/model/settings.py
  conans/test/integration/conanfile/test_attributes_scope.py
  conans/test/integration/graph/core/test_build_require_invalid.py
  conans/test/integration/package_id/test_cache_compatibles.py
  conans/test/integration/package_id/test_validate.py
Labels: type: look into

#12556 [CMakeToolchain] Setting `CMAKE_<LANG>_COMPILER`
  conan/tools/cmake/toolchain/blocks.py
  conan/tools/cmake/toolchain/toolchain.py
  conan/tools/gnu/autotoolstoolchain.py
  conan/tools/meson/toolchain.py
  conans/model/conf.py
  conans/test/functional/toolchains/cmake/test_cmake_toolchain_win_clang.py
  conans/test/functional/toolchains/gnu/autotools/test_win_bash.py
  conans/test/integration/toolchains/cmake/test_cmaketoolchain.py
  conans/test/unittests/tools/cmake/test_cmaketoolchain.py
Labels: type: look into

#11917 CMakeUserPresets custom locations
  conan/tools/cmake/presets.py
  conan/tools/cmake/toolchain/toolchain.py
  conans/test/integration/toolchains/cmake/test_cmaketoolchain.py
Labels: type: feature

#12307 Fix bug with generated pkgconfig files and apple frameworks
  conan/tools/gnu/gnudeps_flags.py
  conans/client/build/compiler_flags.py
  conans/test/functional/toolchains/gnu/test_pkgconfigdeps_autotools.py
  conans/test/unittests/client/build/autotools_environment_test.py
  conans/test/unittests/client/generators/compiler_args_test.py
  conans/test/unittests/client/generators/pkg_config_test.py
  conans/test/unittests/tools/gnu/gnudepsflags_test.py
Labels: stage: triaging

#12598 editables env-vars and confs
  conan/tools/env/environment.py
  conans/client/installer.py
  conans/model/conf.py
  conans/model/layout.py
  conans/test/integration/editable/test_editable_envvars.py
Labels: type: feature
