Repository conan-io/conan, pull requests merged in 2023-12, with the labels that each got.

#14871 New [platform_requires] similar to system-tools, but for all requires
  conan/api/model.py
  conan/cli/printers/graph.py
  conans/client/graph/graph.py
  conans/client/graph/graph_binaries.py
  conans/client/graph/graph_builder.py
  conans/client/installer.py
  conans/client/profile_loader.py
  conans/model/dependencies.py
  conans/model/profile.py
  conans/test/integration/graph/test_platform_requires.py
  conans/test/integration/graph/test_system_tools.py
  conans/test/integration/metadata/test_metadata_collect.py
  conans/test/unittests/client/profile_loader/profile_loader_test.py
Labels: type: feature

#15211 allow hard set_name() set_version()
  conans/client/loader.py
  conans/test/integration/conanfile/set_name_version_test.py
Labels: type: feature

#15136 require-replaces proposal
  conan/cli/printers/graph.py
  conans/client/graph/graph.py
  conans/client/graph/graph_builder.py
  conans/client/profile_loader.py
  conans/model/profile.py
  conans/model/requires.py
  conans/test/integration/graph/test_replace_requires.py
Labels: type: look into

#15214 optimize test
  conan/cli/cli.py
  conans/test/integration/package_id/test_default_package_id.py
  conans/test/utils/tools.py
Labels: type: look into

#15192 Add environment information to CMakePresets
  conan/tools/cmake/presets.py
  conan/tools/cmake/toolchain/toolchain.py
  conan/tools/env/virtualrunenv.py
  conans/model/conf.py
  conans/test/functional/toolchains/cmake/test_cmake_toolchain.py
  conans/test/integration/toolchains/cmake/test_cmaketoolchain.py
  conans/test/unittests/tools/cmake/test_cmaketoolchain.py
Labels: type: feature

#15285 fix self.info.clear() for python_requires and tool_requires
  conans/model/info.py
  conans/test/integration/package_id/package_id_test.py
  conans/test/integration/package_id/python_requires_package_id_test.py
Labels: type: bug

#15319 change default for source_buildenv, too risky
  conans/__init__.py
  conans/client/source.py
  conans/test/integration/build_requires/test_build_requires_source_method.py
Labels: type: look into

#15304 Feature/get commit repo
  conan/tools/scm/git.py
  conans/test/functional/tools/scm/test_git.py
Labels: type: feature
