Repository conan-io/conan, pull requests merged in 2023-10, with the labels that each got.

#14814 Fix/version range pres
  conans/model/version_range.py
  conans/test/integration/graph/version_ranges/test_version_range_conf.py
  conans/test/unittests/model/version/test_version_parse.py
  conans/test/unittests/model/version/test_version_range.py
Labels: type: bug

#14968 increase DB timeout
  conan/internal/cache/db/table.py
Labels: type: look into

#14776 Fix min target flag for xros and xros-simulator
  conan/tools/apple/apple.py
Labels: stage: triaging

#14958 [Bazel][1.x][Part 1]: Bazel + BazelToolchain refactor
  conan/tools/google/bazel.py
  conan/tools/google/layout.py
  conan/tools/google/toolchain.py
  conans/assets/templates/new_v2_bazel.py
  conans/test/functional/toolchains/google/test_bazel.py
  conans/test/functional/toolchains/google/test_bazeltoolchain_cross_compilation.py
  conans/test/functional/toolchains/test_bazel_toolchain.py
  conans/test/integration/toolchains/google/test_bazeldeps.py
  conans/test/integration/toolchains/google/test_bazeltoolchain.py
  conans/test/integration/toolchains/test_toolchain_namespaces.py
  conans/test/unittests/tools/google/test_bazel.py
Labels: type: feature
