Repository conan-io/conan, pull requests merged in 2023-06, with the labels that each got.

#13623 [PkgConfigDeps] Added `bindir` to generated `.pc` files
  conan/tools/gnu/pkgconfigdeps.py
  conans/test/functional/toolchains/gnu/test_pkgconfigdeps.py
  conans/test/integration/layout/test_layout_paths.py
  conans/test/integration/toolchains/gnu/test_pkgconfigdeps.py
Labels: stage: in-progress

#14096 import conan tools improve
  conan/tools/apple/apple.py
  conan/tools/apple/xcodebuild.py
  conan/tools/apple/xcodedeps.py
  conan/tools/build/__init__.py
  conan/tools/build/cppstd.py
  conan/tools/cmake/cmake.py
  conan/tools/cmake/cmakedeps/cmakedeps.py
  conan/tools/cmake/cmakedeps/templates/__init__.py
  conan/tools/cmake/cmakedeps/templates/target_data.py
  conan/tools/cmake/layout.py
  conan/tools/cmake/presets.py
  conan/tools/cmake/toolchain/blocks.py
  conan/tools/cmake/toolchain/toolchain.py
  conan/tools/env/environment.py
  conan/tools/files/conandata.py
  conan/tools/files/files.py
  conan/tools/files/packager.py
  conan/tools/files/patches.py
  conan/tools/gnu/autotoolstoolchain.py
  conan/tools/gnu/get_gnu_triplet.py
  conan/tools/gnu/pkgconfig.py
  conan/tools/gnu/pkgconfigdeps.py
  conan/tools/google/bazeldeps.py
  conan/tools/intel/intel_cc.py
  conan/tools/meson/meson.py
  conan/tools/meson/toolchain.py
  conan/tools/microsoft/layout.py
  conan/tools/microsoft/msbuild.py
  conan/tools/microsoft/msbuilddeps.py
  conan/tools/microsoft/toolchain.py
  conan/tools/microsoft/visual.py
  conan/tools/qbs/qbs.py
  conan/tools/qbs/qbsprofile.py
  conan/tools/scm/git.py
  conan/tools/system/package_manager.py
Labels: type: look into

#14101 make CppInfo an importable tool
  conan/tools/__init__.py
  conan/tools/gnu/autotoolsdeps.py
  conan/tools/microsoft/nmakedeps.py
  conans/model/build_info.py
  conans/test/integration/conanfile/test_cpp_info_serialize.py
Labels: type: feature
