Repository conan-io/conan, pull requests merged in 2023-07, with the labels that each got.

#14167 Fixes #14166: Add strip option to cmake.install tool
  conan/tools/cmake/cmake.py
  conans/test/unittests/tools/cmake/test_cmake_install.py
Labels: type: feature

#14289 Replace 'quiet' cmake loglevel with 'error'
  conan/tools/cmake/cmake.py
Labels: stage: triaging

#14340 fix default_options propagation to test_requires/tool_requires
  conans/client/conanfile/configure.py
  conans/client/graph/graph_builder.py
  conans/model/conan_file.py
  conans/model/options.py
  conans/test/integration/conanfile/test_conanfile_txt_test_requires.py
  conans/test/integration/graph/test_test_requires.py
  conans/test/integration/options/test_options_build_requires.py
  conans/test/unittests/model/options_test.py
Labels: type: look into
