Repository conan-io/conan, pull requests merged in 2024-07, with the labels that each got.

#16573 Ensure msvc fallback does not ignore 194 binaries
  conans/client/graph/compatibility.py
  test/integration/package_id/compatible_test.py
Labels: type: bug

#16575 Fix unexpected error when a recipe performs package_id erasure and is used as a compatibility candidate
  conans/client/graph/graph_binaries.py
  conans/model/settings.py
  test/integration/package_id/compatible_test.py
Labels: type: bug

#16633 build-folder-vars user.value
  conan/tools/cmake/layout.py
  test/integration/toolchains/cmake/test_cmaketoolchain.py
Labels: type: feature

#16597 core.scm:local_url=allow|block
  conan/tools/scm/git.py
  conans/client/cmd/uploader.py
  conans/model/conf.py
  test/functional/tools/scm/test_git.py
Labels: type: bug, type: feature

#16415 Delegate error handling to command framework instead of graph formatters
  conan/cli/command.py
  conan/cli/commands/graph.py
  conan/cli/formatters/graph/build_order_html.py
  conan/cli/formatters/graph/graph.py
  conan/cli/formatters/graph/graph_info_text.py
  conans/client/graph/install_graph.py
  test/integration/command_v2/test_info_build_order.py
Labels: complex: medium, bug
