Repository conan-io/conan, pull requests merged in 2024-05, with the labels that each got.

#15919 [MesonToolchain] Added `native` mechanism when cross-building
  conan/tools/meson/meson.py
  conan/tools/meson/toolchain.py
  conans/client/graph/profile_node_definer.py
  conans/model/conan_file.py
  conans/test/functional/toolchains/meson/test_meson_native_attribute.py
  conans/test/integration/toolchains/meson/test_mesontoolchain.py
Labels: type: feature

#16233 options patterns warning
  conan/api/subapi/profiles.py
  conans/test/integration/command/test_profile.py
  conans/test/integration/options/options_test.py
Labels: type: feature, component: ux

#16132 possibility to require itself, previous version visible=False
  conans/client/graph/graph.py
  conans/test/integration/graph/test_repackaging.py
Labels: type: feature

#16279 let generator overwrite xxxConfig.cmake
  conan/tools/cmake/cmakedeps/cmakedeps.py
  conan/tools/cmake/cmakedeps/templates/config.py
  test/integration/toolchains/cmake/cmakedeps/test_cmakedeps.py
Labels: type: bug
