Repository conan-io/conan, pull requests merged in 2024-06, with the labels that each got.

#16028 Feature/language
  conan/tools/build/__init__.py
  conan/tools/build/cstd.py
  conan/tools/build/flags.py
  conan/tools/cmake/toolchain/blocks.py
  conan/tools/gnu/autotoolstoolchain.py
  conan/tools/meson/helpers.py
  conan/tools/meson/toolchain.py
  conan/tools/microsoft/toolchain.py
  conans/client/conanfile/configure.py
  conans/client/conanfile/implementations.py
  conans/client/conf/__init__.py
  conans/client/graph/compatibility.py
  conans/client/profile_loader.py
  conans/model/conan_file.py
  conans/model/conanfile_interface.py
  test/integration/command_v2/test_inspect.py
  test/integration/package_id/test_cache_compatibles.py
  test/integration/toolchains/meson/test_mesontoolchain.py
  test/unittests/client/toolchain/autotools/autotools_toolchain_test.py
  test/unittests/tools/microsoft/test_msbuild.py
Labels: type: feature

#16425 source credential scope
  conan/api/subapi/upload.py
  conan/test/utils/tools.py
  conans/client/conf/config_installer.py
  conans/client/downloaders/caching_file_downloader.py
  conans/client/downloaders/file_downloader.py
  conans/client/rest/conan_requester.py
  conans/client/rest/file_uploader.py
  test/integration/test_source_download_password.py
Labels: type: look into

#16481 Added force option to tools.cmake.cmaketoolchain:extra_variables
  conan/tools/cmake/toolchain/blocks.py
  test/integration/toolchains/cmake/test_cmaketoolchain.py
Labels: type: feature, complex: low

#16496 CMakeToolchain refactor
  conan/tools/cmake/toolchain/blocks.py
  conan/tools/cmake/toolchain/toolchain.py
  test/unittests/tools/cmake/test_cmaketoolchain.py
Labels: type: look into, type: engineering
